<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        $cities = array(
            array('code' => '05002', 'name' => 'Abejorral', 'department_id' => 2,),
            array('code' => '54003', 'name' => 'Abrego', 'department_id' => 23,),
            array('code' => '05004', 'name' => 'Abriaqui', 'department_id' => 2,),
            array('code' => '50006', 'name' => 'Acacias', 'department_id' => 21,),
            array('code' => '27006', 'name' => 'Acandi', 'department_id' => 13,),
            array('code' => '41006', 'name' => 'Acevedo', 'department_id' => 18,),
            array('code' => '13006', 'name' => 'Achi', 'department_id' => 6,),
            array('code' => '41013', 'name' => 'Agrado', 'department_id' => 18,),
            array('code' => '25001', 'name' => 'Agua De Dios', 'department_id' => 15,),
            array('code' => '20011', 'name' => 'Aguachica', 'department_id' => 12,),
            array('code' => '68013', 'name' => 'Aguada', 'department_id' => 28,),
            array('code' => '17013', 'name' => 'Aguadas', 'department_id' => 8,),
            array('code' => '85010', 'name' => 'Aguazul', 'department_id' => 10,),
            array('code' => '20013', 'name' => 'Agustin Codazzi', 'department_id' => 12,),
            array('code' => '41016', 'name' => 'Aipe', 'department_id' => 18,),
            array('code' => '25019', 'name' => 'Alban', 'department_id' => 15,),
            array('code' => '52019', 'name' => 'Alban', 'department_id' => 22,),
            array('code' => '18029', 'name' => 'Albania', 'department_id' => 9,),
            array('code' => '44035', 'name' => 'Albania', 'department_id' => 19,),
            array('code' => '68020', 'name' => 'Albania', 'department_id' => 28,),
            array('code' => '76020', 'name' => 'Alcala', 'department_id' => 31,),
            array('code' => '52022', 'name' => 'Aldana', 'department_id' => 22,),
            array('code' => '05021', 'name' => 'Alejandria', 'department_id' => 2,),
            array('code' => '47030', 'name' => 'Algarrobo', 'department_id' => 20,),
            array('code' => '41020', 'name' => 'Algeciras', 'department_id' => 18,),
            array('code' => '19022', 'name' => 'Almaguer', 'department_id' => 11,),
            array('code' => '15022', 'name' => 'Almeida', 'department_id' => 7,),
            array('code' => '73024', 'name' => 'Alpujarra', 'department_id' => 30,),
            array('code' => '41026', 'name' => 'Altamira', 'department_id' => 18,),
            array('code' => '27025', 'name' => 'Alto Baudo', 'department_id' => 13,),
            array('code' => '13030', 'name' => 'Altos Del Rosario', 'department_id' => 6,),
            array('code' => '73026', 'name' => 'Alvarado', 'department_id' => 30,),
            array('code' => '05030', 'name' => 'Amaga', 'department_id' => 2,),
            array('code' => '05031', 'name' => 'Amalfi', 'department_id' => 2,),
            array('code' => '73030', 'name' => 'Ambalema', 'department_id' => 30,),
            array('code' => '25035', 'name' => 'Anapoima', 'department_id' => 15,),
            array('code' => '52036', 'name' => 'Ancuya', 'department_id' => 22,),
            array('code' => '76036', 'name' => 'Andalucia', 'department_id' => 31,),
            array('code' => '05034', 'name' => 'Andes', 'department_id' => 2,),
            array('code' => '05036', 'name' => 'Angelopolis', 'department_id' => 2,),
            array('code' => '05038', 'name' => 'Angostura', 'department_id' => 2,),
            array('code' => '25040', 'name' => 'Anolaima', 'department_id' => 15,),
            array('code' => '05040', 'name' => 'Anori', 'department_id' => 2,),
            array('code' => '17042', 'name' => 'Anserma', 'department_id' => 8,),
            array('code' => '76041', 'name' => 'Ansermanuevo', 'department_id' => 31,),
            array('code' => '05044', 'name' => 'Anza', 'department_id' => 2,),
            array('code' => '73043', 'name' => 'Anzoategui', 'department_id' => 30,),
            array('code' => '05045', 'name' => 'Apartado', 'department_id' => 2,),
            array('code' => '66045', 'name' => 'Apia', 'department_id' => 26,),
            array('code' => '25599', 'name' => 'Apulo', 'department_id' => 15,),
            array('code' => '15047', 'name' => 'Aquitania', 'department_id' => 7,),
            array('code' => '47053', 'name' => 'Aracataca', 'department_id' => 20,),
            array('code' => '17050', 'name' => 'Aranzazu', 'department_id' => 8,),
            array('code' => '68051', 'name' => 'Aratoca', 'department_id' => 28,),
            array('code' => '81001', 'name' => 'Arauca', 'department_id' => 3,),
            array('code' => '81065', 'name' => 'Arauquita', 'department_id' => 3,),
            array('code' => '25053', 'name' => 'Arbelaez', 'department_id' => 15,),
            array('code' => '52051', 'name' => 'Arboleda', 'department_id' => 22,),
            array('code' => '54051', 'name' => 'Arboledas', 'department_id' => 23,),
            array('code' => '05051', 'name' => 'Arboletes', 'department_id' => 2,),
            array('code' => '15051', 'name' => 'Arcabuco', 'department_id' => 7,),
            array('code' => '13042', 'name' => 'Arenal', 'department_id' => 6,),
            array('code' => '05055', 'name' => 'Argelia', 'department_id' => 2,),
            array('code' => '19050', 'name' => 'Argelia', 'department_id' => 11,),
            array('code' => '76054', 'name' => 'Argelia', 'department_id' => 31,),
            array('code' => '47058', 'name' => 'Ariguani', 'department_id' => 20,),
            array('code' => '13052', 'name' => 'Arjona', 'department_id' => 6,),
            array('code' => '05059', 'name' => 'Armenia', 'department_id' => 2,),
            array('code' => '63001', 'name' => 'Armenia', 'department_id' => 25,),
            array('code' => '73055', 'name' => 'Armero', 'department_id' => 30,),
            array('code' => '13062', 'name' => 'Arroyohondo', 'department_id' => 6,),
            array('code' => '20032', 'name' => 'Astrea', 'department_id' => 12,),
            array('code' => '73067', 'name' => 'Ataco', 'department_id' => 30,),
            array('code' => '27050', 'name' => 'Atrato', 'department_id' => 13,),
            array('code' => '23068', 'name' => 'Ayapel', 'department_id' => 14,),
            array('code' => '27073', 'name' => 'Bagado', 'department_id' => 13,),
            array('code' => '27075', 'name' => 'Bahia Solano', 'department_id' => 13,),
            array('code' => '27077', 'name' => 'Bajo Baudo', 'department_id' => 13,),
            array('code' => '19075', 'name' => 'Balboa', 'department_id' => 11,),
            array('code' => '66075', 'name' => 'Balboa', 'department_id' => 26,),
            array('code' => '08078', 'name' => 'Baranoa', 'department_id' => 4,),
            array('code' => '41078', 'name' => 'Baraya', 'department_id' => 18,),
            array('code' => '52079', 'name' => 'Barbacoas', 'department_id' => 22,),
            array('code' => '05079', 'name' => 'Barbosa', 'department_id' => 2,),
            array('code' => '68077', 'name' => 'Barbosa', 'department_id' => 28,),
            array('code' => '68079', 'name' => 'Barichara', 'department_id' => 28,),
            array('code' => '50110', 'name' => 'Barranca De Upia', 'department_id' => 21,),
            array('code' => '68081', 'name' => 'Barrancabermeja', 'department_id' => 28,),
            array('code' => '44078', 'name' => 'Barrancas', 'department_id' => 19,),
            array('code' => '13074', 'name' => 'Barranco De Loba', 'department_id' => 6,),
            array('code' => '94343', 'name' => 'Barranco Minas', 'department_id' => 16,),
            array('code' => '08001', 'name' => 'Barranquilla', 'department_id' => 4,),
            array('code' => '20045', 'name' => 'Becerril', 'department_id' => 12,),
            array('code' => '17088', 'name' => 'Belalcazar', 'department_id' => 8,),
            array('code' => '15087', 'name' => 'Belen', 'department_id' => 7,),
            array('code' => '52083', 'name' => 'Belen', 'department_id' => 22,),
            array('code' => '27086', 'name' => 'Belen De Bajira', 'department_id' => 13,),
            array('code' => '18094', 'name' => 'Belen De Los Andaquies', 'department_id' => 9,),
            array('code' => '66088', 'name' => 'Belen De Umbria', 'department_id' => 26,),
            array('code' => '05088', 'name' => 'Bello', 'department_id' => 2,),
            array('code' => '05086', 'name' => 'Belmira', 'department_id' => 2,),
            array('code' => '25086', 'name' => 'Beltran', 'department_id' => 15,),
            array('code' => '15090', 'name' => 'Berbeo', 'department_id' => 7,),
            array('code' => '05091', 'name' => 'Betania', 'department_id' => 2,),
            array('code' => '15092', 'name' => 'Beteitiva', 'department_id' => 7,),
            array('code' => '05093', 'name' => 'Betulia', 'department_id' => 2,),
            array('code' => '68092', 'name' => 'Betulia', 'department_id' => 28,),
            array('code' => '25095', 'name' => 'Bituima', 'department_id' => 15,),
            array('code' => '15097', 'name' => 'Boavita', 'department_id' => 7,),
            array('code' => '54099', 'name' => 'Bochalema', 'department_id' => 23,),
            array('code' => '11001', 'name' => 'Bogota', 'department_id' => 5,),
            array('code' => '25099', 'name' => 'Bojaca', 'department_id' => 15,),
            array('code' => '27099', 'name' => 'Bojaya', 'department_id' => 13,),
            array('code' => '05101', 'name' => 'Bolivar', 'department_id' => 2,),
            array('code' => '19100', 'name' => 'Bolivar', 'department_id' => 11,),
            array('code' => '68101', 'name' => 'Bolivar', 'department_id' => 28,),
            array('code' => '76100', 'name' => 'Bolivar', 'department_id' => 31,),
            array('code' => '20060', 'name' => 'Bosconia', 'department_id' => 12,),
            array('code' => '15104', 'name' => 'Boyaca', 'department_id' => 7,),
            array('code' => '05107', 'name' => 'Briceno', 'department_id' => 2,),
            array('code' => '15106', 'name' => 'Briceno', 'department_id' => 7,),
            array('code' => '68001', 'name' => 'Bucaramanga', 'department_id' => 28,),
            array('code' => '54109', 'name' => 'Bucarasica', 'department_id' => 23,),
            array('code' => '76109', 'name' => 'Buenaventura', 'department_id' => 31,),
            array('code' => '15109', 'name' => 'Buenavista', 'department_id' => 7,),
            array('code' => '23079', 'name' => 'Buenavista', 'department_id' => 14,),
            array('code' => '63111', 'name' => 'Buenavista', 'department_id' => 25,),
            array('code' => '70110', 'name' => 'Buenavista', 'department_id' => 29,),
            array('code' => '19110', 'name' => 'Buenos Aires', 'department_id' => 11,),
            array('code' => '52110', 'name' => 'Buesaco', 'department_id' => 22,),
            array('code' => '76113', 'name' => 'Bugalagrande', 'department_id' => 31,),
            array('code' => '05113', 'name' => 'Buritica', 'department_id' => 2,),
            array('code' => '15114', 'name' => 'Busbanza', 'department_id' => 7,),
            array('code' => '25120', 'name' => 'Cabrera', 'department_id' => 15,),
            array('code' => '68121', 'name' => 'Cabrera', 'department_id' => 28,),
            array('code' => '50124', 'name' => 'Cabuyaro', 'department_id' => 21,),
            array('code' => '94886', 'name' => 'Cacahual', 'department_id' => 16,),
            array('code' => '05120', 'name' => 'Caceres', 'department_id' => 2,),
            array('code' => '25123', 'name' => 'Cachipay', 'department_id' => 15,),
            array('code' => '54128', 'name' => 'Cachira', 'department_id' => 23,),
            array('code' => '54125', 'name' => 'Cacota', 'department_id' => 23,),
            array('code' => '05125', 'name' => 'Caicedo', 'department_id' => 2,),
            array('code' => '76122', 'name' => 'Caicedonia', 'department_id' => 31,),
            array('code' => '70124', 'name' => 'Caimito', 'department_id' => 29,),
            array('code' => '73124', 'name' => 'Cajamarca', 'department_id' => 30,),
            array('code' => '19130', 'name' => 'Cajibio', 'department_id' => 11,),
            array('code' => '25126', 'name' => 'Cajica', 'department_id' => 15,),
            array('code' => '13140', 'name' => 'Calamar', 'department_id' => 6,),
            array('code' => '95015', 'name' => 'Calamar', 'department_id' => 17,),
            array('code' => '63130', 'name' => 'Calarca', 'department_id' => 25,),
            array('code' => '05129', 'name' => 'Caldas', 'department_id' => 2,),
            array('code' => '15131', 'name' => 'Caldas', 'department_id' => 7,),
            array('code' => '19137', 'name' => 'Caldono', 'department_id' => 11,),
            array('code' => '76001', 'name' => 'Cali', 'department_id' => 31,),
            array('code' => '68132', 'name' => 'California', 'department_id' => 28,),
            array('code' => '76126', 'name' => 'Calima', 'department_id' => 31,),
            array('code' => '19142', 'name' => 'Caloto', 'department_id' => 11,),
            array('code' => '05134', 'name' => 'Campamento', 'department_id' => 2,),
            array('code' => '08137', 'name' => 'Campo De La Cruz', 'department_id' => 4,),
            array('code' => '41132', 'name' => 'Campoalegre', 'department_id' => 18,),
            array('code' => '15135', 'name' => 'Campohermoso', 'department_id' => 7,),
            array('code' => '23090', 'name' => 'Canalete', 'department_id' => 14,),
            array('code' => '05138', 'name' => 'Canasgordas', 'department_id' => 2,),
            array('code' => '08141', 'name' => 'Candelaria', 'department_id' => 4,),
            array('code' => '76130', 'name' => 'Candelaria', 'department_id' => 31,),
            array('code' => '13160', 'name' => 'Cantagallo', 'department_id' => 6,),
            array('code' => '25148', 'name' => 'Caparrapi', 'department_id' => 15,),
            array('code' => '68147', 'name' => 'Capitanejo', 'department_id' => 28,),
            array('code' => '25151', 'name' => 'Caqueza', 'department_id' => 15,),
            array('code' => '05142', 'name' => 'Caracoli', 'department_id' => 2,),
            array('code' => '05145', 'name' => 'Caramanta', 'department_id' => 2,),
            array('code' => '68152', 'name' => 'Carcasi', 'department_id' => 28,),
            array('code' => '05147', 'name' => 'Carepa', 'department_id' => 2,),
            array('code' => '73148', 'name' => 'Carmen De Apicala', 'department_id' => 30,),
            array('code' => '25154', 'name' => 'Carmen De Carupa', 'department_id' => 15,),
            array('code' => '27150', 'name' => 'Carmen Del Darien', 'department_id' => 13,),
            array('code' => '05150', 'name' => 'Carolina', 'department_id' => 2,),
            array('code' => '13001', 'name' => 'Cartagena', 'department_id' => 6,),
            array('code' => '18150', 'name' => 'Cartagena Del Chaira', 'department_id' => 9,),
            array('code' => '76147', 'name' => 'Cartago', 'department_id' => 31,),
            array('code' => '97161', 'name' => 'Caruru', 'department_id' => 32,),
            array('code' => '73152', 'name' => 'Casabianca', 'department_id' => 30,),
            array('code' => '50150', 'name' => 'Castilla La Nueva', 'department_id' => 21,),
            array('code' => '05154', 'name' => 'Caucasia', 'department_id' => 2,),
            array('code' => '68160', 'name' => 'Cepita', 'department_id' => 28,),
            array('code' => '23162', 'name' => 'Cerete', 'department_id' => 14,),
            array('code' => '15162', 'name' => 'Cerinza', 'department_id' => 7,),
            array('code' => '68162', 'name' => 'Cerrito', 'department_id' => 28,),
            array('code' => '47161', 'name' => 'Cerro San Antonio', 'department_id' => 20,),
            array('code' => '27160', 'name' => 'Certegui', 'department_id' => 13,),
            array('code' => '52240', 'name' => 'Chachagni', 'department_id' => 22,),
            array('code' => '25168', 'name' => 'Chaguani', 'department_id' => 15,),
            array('code' => '70230', 'name' => 'Chalan', 'department_id' => 29,),
            array('code' => '85015', 'name' => 'Chameza', 'department_id' => 10,),
            array('code' => '73168', 'name' => 'Chaparral', 'department_id' => 30,),
            array('code' => '68167', 'name' => 'Charala', 'department_id' => 28,),
            array('code' => '68169', 'name' => 'Charta', 'department_id' => 28,),
            array('code' => '25175', 'name' => 'Chia', 'department_id' => 15,),
            array('code' => '47170', 'name' => 'Chibolo', 'department_id' => 20,),
            array('code' => '05172', 'name' => 'Chigorodo', 'department_id' => 2,),
            array('code' => '23168', 'name' => 'Chima', 'department_id' => 14,),
            array('code' => '68176', 'name' => 'Chima', 'department_id' => 28,),
            array('code' => '20175', 'name' => 'Chimichagua', 'department_id' => 12,),
            array('code' => '54172', 'name' => 'Chinacota', 'department_id' => 23,),
            array('code' => '15172', 'name' => 'Chinavita', 'department_id' => 7,),
            array('code' => '17174', 'name' => 'Chinchina', 'department_id' => 8,),
            array('code' => '23182', 'name' => 'Chinu', 'department_id' => 14,),
            array('code' => '25178', 'name' => 'Chipaque', 'department_id' => 15,),
            array('code' => '68179', 'name' => 'Chipata', 'department_id' => 28,),
            array('code' => '15176', 'name' => 'Chiquinquira', 'department_id' => 7,),
            array('code' => '15232', 'name' => 'Chiquiza', 'department_id' => 7,),
            array('code' => '20178', 'name' => 'Chiriguana', 'department_id' => 12,),
            array('code' => '15180', 'name' => 'Chiscas', 'department_id' => 7,),
            array('code' => '15183', 'name' => 'Chita', 'department_id' => 7,),
            array('code' => '54174', 'name' => 'Chitaga', 'department_id' => 23,),
            array('code' => '15185', 'name' => 'Chitaraque', 'department_id' => 7,),
            array('code' => '15187', 'name' => 'Chivata', 'department_id' => 7,),
            array('code' => '15236', 'name' => 'Chivor', 'department_id' => 7,),
            array('code' => '25181', 'name' => 'Choachi', 'department_id' => 15,),
            array('code' => '25183', 'name' => 'Choconta', 'department_id' => 15,),
            array('code' => '13188', 'name' => 'Cicuco', 'department_id' => 6,),
            array('code' => '47189', 'name' => 'Cienaga', 'department_id' => 20,),
            array('code' => '23189', 'name' => 'Cienaga De Oro', 'department_id' => 14,),
            array('code' => '15189', 'name' => 'Cienega', 'department_id' => 7,),
            array('code' => '68190', 'name' => 'Cimitarra', 'department_id' => 28,),
            array('code' => '63190', 'name' => 'Circasia', 'department_id' => 25,),
            array('code' => '05190', 'name' => 'Cisneros', 'department_id' => 2,),
            array('code' => '13222', 'name' => 'Clemencia', 'department_id' => 6,),
            array('code' => '05197', 'name' => 'Cocorna', 'department_id' => 2,),
            array('code' => '73200', 'name' => 'Coello', 'department_id' => 30,),
            array('code' => '25200', 'name' => 'Cogua', 'department_id' => 15,),
            array('code' => '41206', 'name' => 'Colombia', 'department_id' => 18,),
            array('code' => '52203', 'name' => 'Colon', 'department_id' => 22,),
            array('code' => '86219', 'name' => 'Colon', 'department_id' => 24,),
            array('code' => '70204', 'name' => 'Coloso', 'department_id' => 29,),
            array('code' => '15204', 'name' => 'Combita', 'department_id' => 7,),
            array('code' => '05206', 'name' => 'Concepcion', 'department_id' => 2,),
            array('code' => '68207', 'name' => 'Concepcion', 'department_id' => 28,),
            array('code' => '05209', 'name' => 'Concordia', 'department_id' => 2,),
            array('code' => '47205', 'name' => 'Concordia', 'department_id' => 20,),
            array('code' => '27205', 'name' => 'Condoto', 'department_id' => 13,),
            array('code' => '68209', 'name' => 'Confines', 'department_id' => 28,),
            array('code' => '52207', 'name' => 'Consaca', 'department_id' => 22,),
            array('code' => '52210', 'name' => 'Contadero', 'department_id' => 22,),
            array('code' => '68211', 'name' => 'Contratacion', 'department_id' => 28,),
            array('code' => '54206', 'name' => 'Convencion', 'department_id' => 23,),
            array('code' => '05212', 'name' => 'Copacabana', 'department_id' => 2,),
            array('code' => '15212', 'name' => 'Coper', 'department_id' => 7,),
            array('code' => '13212', 'name' => 'Cordoba', 'department_id' => 6,),
            array('code' => '52215', 'name' => 'Cordoba', 'department_id' => 22,),
            array('code' => '63212', 'name' => 'Cordoba', 'department_id' => 25,),
            array('code' => '19212', 'name' => 'Corinto', 'department_id' => 11,),
            array('code' => '68217', 'name' => 'Coromoro', 'department_id' => 28,),
            array('code' => '70215', 'name' => 'Corozal', 'department_id' => 29,),
            array('code' => '15215', 'name' => 'Corrales', 'department_id' => 7,),
            array('code' => '25214', 'name' => 'Cota', 'department_id' => 15,),
            array('code' => '23300', 'name' => 'Cotorra', 'department_id' => 14,),
            array('code' => '15218', 'name' => 'Covarachia', 'department_id' => 7,),
            array('code' => '70221', 'name' => 'Covenas', 'department_id' => 29,),
            array('code' => '73217', 'name' => 'Coyaima', 'department_id' => 30,),
            array('code' => '81220', 'name' => 'Cravo Norte', 'department_id' => 3,),
            array('code' => '52224', 'name' => 'Cuaspud', 'department_id' => 22,),
            array('code' => '15223', 'name' => 'Cubara', 'department_id' => 7,),
            array('code' => '50223', 'name' => 'Cubarral', 'department_id' => 21,),
            array('code' => '15224', 'name' => 'Cucaita', 'department_id' => 7,),
            array('code' => '25224', 'name' => 'Cucunuba', 'department_id' => 15,),
            array('code' => '54001', 'name' => 'Cucuta', 'department_id' => 23,),
            array('code' => '54223', 'name' => 'Cucutilla', 'department_id' => 23,),
            array('code' => '15226', 'name' => 'Cuitiva', 'department_id' => 7,),
            array('code' => '50226', 'name' => 'Cumaral', 'department_id' => 21,),
            array('code' => '99773', 'name' => 'Cumaribo    ', 'department_id' => 33,),
            array('code' => '52227', 'name' => 'Cumbal', 'department_id' => 22,),
            array('code' => '52233', 'name' => 'Cumbitara', 'department_id' => 22,),
            array('code' => '73226', 'name' => 'Cunday', 'department_id' => 30,),
            array('code' => '18205', 'name' => 'Curillo', 'department_id' => 9,),
            array('code' => '68229', 'name' => 'Curiti', 'department_id' => 28,),
            array('code' => '20228', 'name' => 'Curumani', 'department_id' => 12,),
            array('code' => '05234', 'name' => 'Dabeiba', 'department_id' => 2,),
            array('code' => '76233', 'name' => 'Dagua', 'department_id' => 31,),
            array('code' => '44090', 'name' => 'Dibulla', 'department_id' => 19,),
            array('code' => '44098', 'name' => 'Distraccion', 'department_id' => 19,),
            array('code' => '73236', 'name' => 'Dolores', 'department_id' => 30,),
            array('code' => '05237', 'name' => 'Don Matias', 'department_id' => 2,),
            array('code' => '66170', 'name' => 'Dosquebradas', 'department_id' => 26,),
            array('code' => '15238', 'name' => 'Duitama', 'department_id' => 7,),
            array('code' => '54239', 'name' => 'Durania', 'department_id' => 23,),
            array('code' => '05240', 'name' => 'Ebejico', 'department_id' => 2,),
            array('code' => '76243', 'name' => 'El Aguila', 'department_id' => 31,),
            array('code' => '05250', 'name' => 'El Bagre', 'department_id' => 2,),
            array('code' => '47245', 'name' => 'El Banco', 'department_id' => 20,),
            array('code' => '76246', 'name' => 'El Cairo', 'department_id' => 31,),
            array('code' => '50245', 'name' => 'El Calvario', 'department_id' => 21,),
            array('code' => '27135', 'name' => 'El Canton Del San Pablo', 'department_id' => 13,),
            array('code' => '54245', 'name' => 'El Carmen', 'department_id' => 23,),
            array('code' => '27245', 'name' => 'El Carmen De Atrato', 'department_id' => 13,),
            array('code' => '13244', 'name' => 'El Carmen De Bolivar', 'department_id' => 6,),
            array('code' => '68235', 'name' => 'El Carmen De Chucuri', 'department_id' => 28,),
            array('code' => '05148', 'name' => 'El Carmen De Viboral', 'department_id' => 2,),
            array('code' => '50251', 'name' => 'El Castillo', 'department_id' => 21,),
            array('code' => '76248', 'name' => 'El Cerrito', 'department_id' => 31,),
            array('code' => '52250', 'name' => 'El Charco', 'department_id' => 22,),
            array('code' => '15244', 'name' => 'El Cocuy', 'department_id' => 7,),
            array('code' => '25245', 'name' => 'El Colegio', 'department_id' => 15,),
            array('code' => '20238', 'name' => 'El Copey', 'department_id' => 12,),
            array('code' => '18247', 'name' => 'El Doncello', 'department_id' => 9,),
            array('code' => '50270', 'name' => 'El Dorado', 'department_id' => 21,),
            array('code' => '76250', 'name' => 'El Dovio', 'department_id' => 31,),
            array('code' => '91263', 'name' => 'El Encanto', 'department_id' => 1,),
            array('code' => '15248', 'name' => 'El Espino', 'department_id' => 7,),
            array('code' => '68245', 'name' => 'El Guacamayo', 'department_id' => 28,),
            array('code' => '13248', 'name' => 'El Guamo', 'department_id' => 6,),
            array('code' => '27250', 'name' => 'El Litoral Del San Juan', 'department_id' => 13,),
            array('code' => '44110', 'name' => 'El Molino', 'department_id' => 19,),
            array('code' => '20250', 'name' => 'El Paso', 'department_id' => 12,),
            array('code' => '18256', 'name' => 'El Paujil', 'department_id' => 9,),
            array('code' => '52254', 'name' => 'El Penol', 'department_id' => 22,),
            array('code' => '13268', 'name' => 'El Penon', 'department_id' => 6,),
            array('code' => '25258', 'name' => 'El Penon', 'department_id' => 15,),
            array('code' => '68250', 'name' => 'El Penon', 'department_id' => 28,),
            array('code' => '47258', 'name' => 'El Pinon', 'department_id' => 20,),
            array('code' => '68255', 'name' => 'El Playon', 'department_id' => 28,),
            array('code' => '47268', 'name' => 'El Reten', 'department_id' => 20,),
            array('code' => '95025', 'name' => 'El Retorno', 'department_id' => 17,),
            array('code' => '70233', 'name' => 'El Roble', 'department_id' => 29,),
            array('code' => '25260', 'name' => 'El Rosal', 'department_id' => 15,),
            array('code' => '52256', 'name' => 'El Rosario', 'department_id' => 22,),
            array('code' => '05697', 'name' => 'El Santuario', 'department_id' => 2,),
            array('code' => '52258', 'name' => 'El Tablon De Gomez', 'department_id' => 22,),
            array('code' => '19256', 'name' => 'El Tambo', 'department_id' => 11,),
            array('code' => '52260', 'name' => 'El Tambo', 'department_id' => 22,),
            array('code' => '54250', 'name' => 'El Tarra', 'department_id' => 23,),
            array('code' => '54261', 'name' => 'El Zulia', 'department_id' => 23,),
            array('code' => '41244', 'name' => 'Elias', 'department_id' => 18,),
            array('code' => '68264', 'name' => 'Encino', 'department_id' => 28,),
            array('code' => '68266', 'name' => 'Enciso', 'department_id' => 28,),
            array('code' => '05264', 'name' => 'Entrerrios', 'department_id' => 2,),
            array('code' => '05266', 'name' => 'Envigado', 'department_id' => 2,),
            array('code' => '73268', 'name' => 'Espinal', 'department_id' => 30,),
            array('code' => '25288', 'name' => 'F;Quene', 'department_id' => 15,),
            array('code' => '25269', 'name' => 'Facatativa', 'department_id' => 15,),
            array('code' => '73270', 'name' => 'Falan', 'department_id' => 30,),
            array('code' => '17272', 'name' => 'Filadelfia', 'department_id' => 8,),
            array('code' => '63272', 'name' => 'Filandia', 'department_id' => 25,),
            array('code' => '15272', 'name' => 'Firavitoba', 'department_id' => 7,),
            array('code' => '73275', 'name' => 'Flandes', 'department_id' => 30,),
            array('code' => '18001', 'name' => 'Florencia', 'department_id' => 9,),
            array('code' => '19290', 'name' => 'Florencia', 'department_id' => 11,),
            array('code' => '15276', 'name' => 'Floresta', 'department_id' => 7,),
            array('code' => '68271', 'name' => 'Florian', 'department_id' => 28,),
            array('code' => '76275', 'name' => 'Florida', 'department_id' => 31,),
            array('code' => '68276', 'name' => 'Floridablanca', 'department_id' => 28,),
            array('code' => '25279', 'name' => 'Fomeque', 'department_id' => 15,),
            array('code' => '44279', 'name' => 'Fonseca', 'department_id' => 19,),
            array('code' => '81300', 'name' => 'Fortul', 'department_id' => 3,),
            array('code' => '25281', 'name' => 'Fosca', 'department_id' => 15,),
            array('code' => '52520', 'name' => 'Francisco Pizarro', 'department_id' => 22,),
            array('code' => '05282', 'name' => 'Fredonia', 'department_id' => 2,),
            array('code' => '73283', 'name' => 'Fresno', 'department_id' => 30,),
            array('code' => '05284', 'name' => 'Frontino', 'department_id' => 2,),
            array('code' => '50287', 'name' => 'Fuente De Oro', 'department_id' => 21,),
            array('code' => '47288', 'name' => 'Fundacion', 'department_id' => 20,),
            array('code' => '52287', 'name' => 'Funes', 'department_id' => 22,),
            array('code' => '25286', 'name' => 'Funza', 'department_id' => 15,),
            array('code' => '25290', 'name' => 'Fusagasuga', 'department_id' => 15,),
            array('code' => '25293', 'name' => 'Gachala', 'department_id' => 15,),
            array('code' => '25295', 'name' => 'Gachancipa', 'department_id' => 15,),
            array('code' => '15293', 'name' => 'Gachantiva', 'department_id' => 7,),
            array('code' => '25297', 'name' => 'Gacheta', 'department_id' => 15,),
            array('code' => '68296', 'name' => 'Galan', 'department_id' => 28,),
            array('code' => '08296', 'name' => 'Galapa', 'department_id' => 4,),
            array('code' => '70235', 'name' => 'Galeras', 'department_id' => 29,),
            array('code' => '25299', 'name' => 'Gama', 'department_id' => 15,),
            array('code' => '20295', 'name' => 'Gamarra', 'department_id' => 12,),
            array('code' => '68298', 'name' => 'Gambita', 'department_id' => 28,),
            array('code' => '15296', 'name' => 'Gameza', 'department_id' => 7,),
            array('code' => '15299', 'name' => 'Garagoa', 'department_id' => 7,),
            array('code' => '41298', 'name' => 'Garzon', 'department_id' => 18,),
            array('code' => '63302', 'name' => 'Genova', 'department_id' => 25,),
            array('code' => '41306', 'name' => 'Gigante', 'department_id' => 18,),
            array('code' => '76306', 'name' => 'Ginebra', 'department_id' => 31,),
            array('code' => '05306', 'name' => 'Giraldo', 'department_id' => 2,),
            array('code' => '25307', 'name' => 'Girardot', 'department_id' => 15,),
            array('code' => '05308', 'name' => 'Girardota', 'department_id' => 2,),
            array('code' => '68307', 'name' => 'Giron', 'department_id' => 28,),
            array('code' => '68327', 'name' => 'Gnepsa', 'department_id' => 28,),
            array('code' => '15332', 'name' => 'Gnican', 'department_id' => 7,),
            array('code' => '05310', 'name' => 'Gomez Plata', 'department_id' => 2,),
            array('code' => '20310', 'name' => 'Gonzalez', 'department_id' => 12,),
            array('code' => '54313', 'name' => 'Gramalote', 'department_id' => 23,),
            array('code' => '05313', 'name' => 'Granada', 'department_id' => 2,),
            array('code' => '25312', 'name' => 'Granada', 'department_id' => 15,),
            array('code' => '50313', 'name' => 'Granada', 'department_id' => 21,),
            array('code' => '68318', 'name' => 'Guaca', 'department_id' => 28,),
            array('code' => '15317', 'name' => 'Guacamayas', 'department_id' => 7,),
            array('code' => '76318', 'name' => 'Guacari', 'department_id' => 31,),
            array('code' => '25317', 'name' => 'Guacheta', 'department_id' => 15,),
            array('code' => '52317', 'name' => 'Guachucal', 'department_id' => 22,),
            array('code' => '76111', 'name' => 'Guadalajara De Buga', 'department_id' => 31,),
            array('code' => '05315', 'name' => 'Guadalupe', 'department_id' => 2,),
            array('code' => '41319', 'name' => 'Guadalupe', 'department_id' => 18,),
            array('code' => '68320', 'name' => 'Guadalupe', 'department_id' => 28,),
            array('code' => '25320', 'name' => 'Guaduas', 'department_id' => 15,),
            array('code' => '52320', 'name' => 'Guaitarilla', 'department_id' => 22,),
            array('code' => '52323', 'name' => 'Gualmatan', 'department_id' => 22,),
            array('code' => '47318', 'name' => 'Guamal', 'department_id' => 20,),
            array('code' => '50318', 'name' => 'Guamal', 'department_id' => 21,),
            array('code' => '73319', 'name' => 'Guamo', 'department_id' => 30,),
            array('code' => '19318', 'name' => 'Guapi', 'department_id' => 11,),
            array('code' => '68322', 'name' => 'Guapota', 'department_id' => 28,),
            array('code' => '70265', 'name' => 'Guaranda', 'department_id' => 29,),
            array('code' => '05318', 'name' => 'Guarne', 'department_id' => 2,),
            array('code' => '25322', 'name' => 'Guasca', 'department_id' => 15,),
            array('code' => '05321', 'name' => 'Guatape', 'department_id' => 2,),
            array('code' => '25324', 'name' => 'Guataqui', 'department_id' => 15,),
            array('code' => '25326', 'name' => 'Guatavita', 'department_id' => 15,),
            array('code' => '15322', 'name' => 'Guateque', 'department_id' => 7,),
            array('code' => '66318', 'name' => 'Guatica', 'department_id' => 26,),
            array('code' => '68324', 'name' => 'Guavata', 'department_id' => 28,),
            array('code' => '25328', 'name' => 'Guayabal De Siquima', 'department_id' => 15,),
            array('code' => '25335', 'name' => 'Guayabetal', 'department_id' => 15,),
            array('code' => '15325', 'name' => 'Guayata', 'department_id' => 7,),
            array('code' => '25339', 'name' => 'Gutierrez', 'department_id' => 15,),
            array('code' => '54344', 'name' => 'Hacari', 'department_id' => 23,),
            array('code' => '13300', 'name' => 'Hatillo De Loba', 'department_id' => 6,),
            array('code' => '68344', 'name' => 'Hato', 'department_id' => 28,),
            array('code' => '85125', 'name' => 'Hato Corozal', 'department_id' => 10,),
            array('code' => '44378', 'name' => 'Hatonuevo', 'department_id' => 19,),
            array('code' => '05347', 'name' => 'Heliconia', 'department_id' => 2,),
            array('code' => '54347', 'name' => 'Herran', 'department_id' => 23,),
            array('code' => '73347', 'name' => 'Herveo', 'department_id' => 30,),
            array('code' => '05353', 'name' => 'Hispania', 'department_id' => 2,),
            array('code' => '41349', 'name' => 'Hobo', 'department_id' => 18,),
            array('code' => '73349', 'name' => 'Honda', 'department_id' => 30,),
            array('code' => '73001', 'name' => 'Ibague', 'department_id' => 30,),
            array('code' => '73352', 'name' => 'Icononzo', 'department_id' => 30,),
            array('code' => '52352', 'name' => 'Iles', 'department_id' => 22,),
            array('code' => '52354', 'name' => 'Imues', 'department_id' => 22,),
            array('code' => '94001', 'name' => 'Inirida', 'department_id' => 16,),
            array('code' => '19355', 'name' => 'Inza', 'department_id' => 11,),
            array('code' => '52356', 'name' => 'Ipiales', 'department_id' => 22,),
            array('code' => '41357', 'name' => 'Iquira', 'department_id' => 18,),
            array('code' => '41359', 'name' => 'Isnos', 'department_id' => 18,),
            array('code' => '27361', 'name' => 'Istmina', 'department_id' => 13,),
            array('code' => '05360', 'name' => 'Itagui', 'department_id' => 2,),
            array('code' => '05361', 'name' => 'Ituango', 'department_id' => 2,),
            array('code' => '15362', 'name' => 'Iza', 'department_id' => 7,),
            array('code' => '19364', 'name' => 'Jambalo', 'department_id' => 11,),
            array('code' => '76364', 'name' => 'Jamundi', 'department_id' => 31,),
            array('code' => '05364', 'name' => 'Jardin', 'department_id' => 2,),
            array('code' => '15367', 'name' => 'Jenesano', 'department_id' => 7,),
            array('code' => '05368', 'name' => 'Jerico', 'department_id' => 2,),
            array('code' => '15368', 'name' => 'Jerico', 'department_id' => 7,),
            array('code' => '25368', 'name' => 'Jerusalen', 'department_id' => 15,),
            array('code' => '68368', 'name' => 'Jes;S Maria', 'department_id' => 28,),
            array('code' => '68370', 'name' => 'Jordan', 'department_id' => 28,),
            array('code' => '08372', 'name' => 'Juan De Acosta', 'department_id' => 4,),
            array('code' => '25372', 'name' => 'Junin', 'department_id' => 15,),
            array('code' => '27372', 'name' => 'Jurado', 'department_id' => 13,),
            array('code' => '23350', 'name' => 'La Apartada', 'department_id' => 14,),
            array('code' => '41378', 'name' => 'La Argentina', 'department_id' => 18,),
            array('code' => '68377', 'name' => 'La Belleza', 'department_id' => 28,),
            array('code' => '25377', 'name' => 'La Calera', 'department_id' => 15,),
            array('code' => '15380', 'name' => 'La Capilla', 'department_id' => 7,),
            array('code' => '05376', 'name' => 'La Ceja', 'department_id' => 2,),
            array('code' => '66383', 'name' => 'La Celia', 'department_id' => 26,),
            array('code' => '91405', 'name' => 'La Chorrera', 'department_id' => 1,),
            array('code' => '52378', 'name' => 'La Cruz', 'department_id' => 22,),
            array('code' => '76377', 'name' => 'La Cumbre', 'department_id' => 31,),
            array('code' => '17380', 'name' => 'La Dorada', 'department_id' => 8,),
            array('code' => '54385', 'name' => 'La Esperanza', 'department_id' => 23,),
            array('code' => '05380', 'name' => 'La Estrella', 'department_id' => 2,),
            array('code' => '52381', 'name' => 'La Florida', 'department_id' => 22,),
            array('code' => '20383', 'name' => 'La Gloria', 'department_id' => 12,),
            array('code' => '94885', 'name' => 'La Guadalupe', 'department_id' => 16,),
            array('code' => '20400', 'name' => 'La Jagua De Ibirico', 'department_id' => 12,),
            array('code' => '44420', 'name' => 'La Jagua Del Pilar', 'department_id' => 19,),
            array('code' => '52385', 'name' => 'La Llanada', 'department_id' => 22,),
            array('code' => '50350', 'name' => 'La Macarena', 'department_id' => 21,),
            array('code' => '17388', 'name' => 'La Merced', 'department_id' => 8,),
            array('code' => '25386', 'name' => 'La Mesa', 'department_id' => 15,),
            array('code' => '18410', 'name' => 'La Montanita', 'department_id' => 9,),
            array('code' => '25394', 'name' => 'La Palma', 'department_id' => 15,),
            array('code' => '20621', 'name' => 'La Paz', 'department_id' => 12,),
            array('code' => '68397', 'name' => 'La Paz', 'department_id' => 28,),
            array('code' => '91407', 'name' => 'La Pedrera', 'department_id' => 1,),
            array('code' => '25398', 'name' => 'La Pena', 'department_id' => 15,),
            array('code' => '05390', 'name' => 'La Pintada', 'department_id' => 2,),
            array('code' => '41396', 'name' => 'La Plata', 'department_id' => 18,),
            array('code' => '54398', 'name' => 'La Playa', 'department_id' => 23,),
            array('code' => '99524', 'name' => 'La Primavera', 'department_id' => 33,),
            array('code' => '85136', 'name' => 'La Salina', 'department_id' => 10,),
            array('code' => '19392', 'name' => 'La Sierra', 'department_id' => 11,),
            array('code' => '63401', 'name' => 'La Tebaida', 'department_id' => 25,),
            array('code' => '52390', 'name' => 'La Tola', 'department_id' => 22,),
            array('code' => '05400', 'name' => 'La Union', 'department_id' => 2,),
            array('code' => '52399', 'name' => 'La Union', 'department_id' => 22,),
            array('code' => '70400', 'name' => 'La Union', 'department_id' => 29,),
            array('code' => '76400', 'name' => 'La Union', 'department_id' => 31,),
            array('code' => '15403', 'name' => 'La Uvita', 'department_id' => 7,),
            array('code' => '19397', 'name' => 'La Vega', 'department_id' => 11,),
            array('code' => '25402', 'name' => 'La Vega', 'department_id' => 15,),
            array('code' => '15401', 'name' => 'La Victoria', 'department_id' => 7,),
            array('code' => '76403', 'name' => 'La Victoria', 'department_id' => 31,),
            array('code' => '91430', 'name' => 'La Victoria', 'department_id' => 1,),
            array('code' => '66400', 'name' => 'La Virginia', 'department_id' => 26,),
            array('code' => '54377', 'name' => 'Labateca', 'department_id' => 23,),
            array('code' => '15377', 'name' => 'Labranzagrande', 'department_id' => 7,),
            array('code' => '68385', 'name' => 'Landazuri', 'department_id' => 28,),
            array('code' => '68406', 'name' => 'Lebrija', 'department_id' => 28,),
            array('code' => '86573', 'name' => 'Leguizamo', 'department_id' => 24,),
            array('code' => '52405', 'name' => 'Leiva', 'department_id' => 22,),
            array('code' => '50400', 'name' => 'Lejanias', 'department_id' => 21,),
            array('code' => '25407', 'name' => 'Lenguazaque', 'department_id' => 15,),
            array('code' => '73408', 'name' => 'Lerida', 'department_id' => 30,),
            array('code' => '91001', 'name' => 'Leticia', 'department_id' => 1,),
            array('code' => '73411', 'name' => 'Libano', 'department_id' => 30,),
            array('code' => '05411', 'name' => 'Liborina', 'department_id' => 2,),
            array('code' => '52411', 'name' => 'Linares', 'department_id' => 22,),
            array('code' => '27413', 'name' => 'Lloro', 'department_id' => 13,),
            array('code' => '19418', 'name' => 'Lopez', 'department_id' => 11,),
            array('code' => '23417', 'name' => 'Lorica', 'department_id' => 14,),
            array('code' => '52418', 'name' => 'Los Andes', 'department_id' => 22,),
            array('code' => '23419', 'name' => 'Los Cordobas', 'department_id' => 14,),
            array('code' => '70418', 'name' => 'Los Palmitos', 'department_id' => 29,),
            array('code' => '54405', 'name' => 'Los Patios', 'department_id' => 23,),
            array('code' => '68418', 'name' => 'Los Santos', 'department_id' => 28,),
            array('code' => '54418', 'name' => 'Lourdes', 'department_id' => 23,),
            array('code' => '08421', 'name' => 'Luruaco', 'department_id' => 4,),
            array('code' => '15425', 'name' => 'Macanal', 'department_id' => 7,),
            array('code' => '68425', 'name' => 'Macaravita', 'department_id' => 28,),
            array('code' => '05425', 'name' => 'Maceo', 'department_id' => 2,),
            array('code' => '25426', 'name' => 'Macheta', 'department_id' => 15,),
            array('code' => '25430', 'name' => 'Madrid', 'department_id' => 15,),
            array('code' => '13430', 'name' => 'Magangue', 'department_id' => 6,),
            array('code' => '52427', 'name' => 'Magni', 'department_id' => 22,),
            array('code' => '13433', 'name' => 'Mahates', 'department_id' => 6,),
            array('code' => '44430', 'name' => 'Maicao', 'department_id' => 19,),
            array('code' => '70429', 'name' => 'Majagual', 'department_id' => 29,),
            array('code' => '68432', 'name' => 'Malaga', 'department_id' => 28,),
            array('code' => '08433', 'name' => 'Malambo', 'department_id' => 4,),
            array('code' => '52435', 'name' => 'Mallama', 'department_id' => 22,),
            array('code' => '08436', 'name' => 'Manati', 'department_id' => 4,),
            array('code' => '20443', 'name' => 'Manaure', 'department_id' => 12,),
            array('code' => '44560', 'name' => 'Manaure', 'department_id' => 19,),
            array('code' => '85139', 'name' => 'Mani', 'department_id' => 10,),
            array('code' => '17001', 'name' => 'Manizales', 'department_id' => 8,),
            array('code' => '25436', 'name' => 'Manta', 'department_id' => 15,),
            array('code' => '17433', 'name' => 'Manzanares', 'department_id' => 8,),
            array('code' => '50325', 'name' => 'Mapiripan', 'department_id' => 21,),
            array('code' => '94663', 'name' => 'Mapiripana', 'department_id' => 16,),
            array('code' => '13440', 'name' => 'Margarita', 'department_id' => 6,),
            array('code' => '13442', 'name' => 'Maria La Baja', 'department_id' => 6,),
            array('code' => '05440', 'name' => 'Marinilla', 'department_id' => 2,),
            array('code' => '15442', 'name' => 'Maripi', 'department_id' => 7,),
            array('code' => '73443', 'name' => 'Mariquita', 'department_id' => 30,),
            array('code' => '17442', 'name' => 'Marmato', 'department_id' => 8,),
            array('code' => '17444', 'name' => 'Marquetalia', 'department_id' => 8,),
            array('code' => '66440', 'name' => 'Marsella', 'department_id' => 26,),
            array('code' => '17446', 'name' => 'Marulanda', 'department_id' => 8,),
            array('code' => '68444', 'name' => 'Matanza', 'department_id' => 28,),
            array('code' => '05001', 'name' => 'Medellin', 'department_id' => 2,),
            array('code' => '25438', 'name' => 'Medina', 'department_id' => 15,),
            array('code' => '27425', 'name' => 'Medio Atrato', 'department_id' => 13,),
            array('code' => '27430', 'name' => 'Medio Baudo', 'department_id' => 13,),
            array('code' => '27450', 'name' => 'Medio San Juan', 'department_id' => 13,),
            array('code' => '73449', 'name' => 'Melgar', 'department_id' => 30,),
            array('code' => '19450', 'name' => 'Mercaderes', 'department_id' => 11,),
            array('code' => '50330', 'name' => 'Mesetas', 'department_id' => 21,),
            array('code' => '18460', 'name' => 'Milan', 'department_id' => 9,),
            array('code' => '15455', 'name' => 'Miraflores', 'department_id' => 7,),
            array('code' => '95200', 'name' => 'Miraflores', 'department_id' => 17,),
            array('code' => '19455', 'name' => 'Miranda', 'department_id' => 11,),
            array('code' => '91460', 'name' => 'Miriti - Parana', 'department_id' => 1,),
            array('code' => '66456', 'name' => 'Mistrato', 'department_id' => 26,),
            array('code' => '97001', 'name' => 'Mitu', 'department_id' => 32,),
            array('code' => '86001', 'name' => 'Mocoa', 'department_id' => 24,),
            array('code' => '68464', 'name' => 'Mogotes', 'department_id' => 28,),
            array('code' => '68468', 'name' => 'Molagavita', 'department_id' => 28,),
            array('code' => '23464', 'name' => 'Momil', 'department_id' => 14,),
            array('code' => '13468', 'name' => 'Mompos', 'department_id' => 6,),
            array('code' => '15464', 'name' => 'Mongua', 'department_id' => 7,),
            array('code' => '15466', 'name' => 'Mongui', 'department_id' => 7,),
            array('code' => '15469', 'name' => 'Moniquira', 'department_id' => 7,),
            array('code' => '23500', 'name' => 'Monitos', 'department_id' => 14,),
            array('code' => '05467', 'name' => 'Montebello', 'department_id' => 2,),
            array('code' => '13458', 'name' => 'Montecristo', 'department_id' => 6,),
            array('code' => '23466', 'name' => 'Montelibano', 'department_id' => 14,),
            array('code' => '63470', 'name' => 'Montenegro', 'department_id' => 25,),
            array('code' => '23001', 'name' => 'Monteria', 'department_id' => 14,),
            array('code' => '85162', 'name' => 'Monterrey', 'department_id' => 10,),
            array('code' => '13473', 'name' => 'Morales', 'department_id' => 6,),
            array('code' => '19473', 'name' => 'Morales', 'department_id' => 11,),
            array('code' => '18479', 'name' => 'Morelia', 'department_id' => 9,),
            array('code' => '94888', 'name' => 'Morichal', 'department_id' => 16,),
            array('code' => '70473', 'name' => 'Morroa', 'department_id' => 29,),
            array('code' => '25473', 'name' => 'Mosquera', 'department_id' => 15,),
            array('code' => '52473', 'name' => 'Mosquera', 'department_id' => 22,),
            array('code' => '15476', 'name' => 'Motavita', 'department_id' => 7,),
            array('code' => '73461', 'name' => 'Murillo', 'department_id' => 30,),
            array('code' => '05475', 'name' => 'Murindo', 'department_id' => 2,),
            array('code' => '05480', 'name' => 'Mutata', 'department_id' => 2,),
            array('code' => '54480', 'name' => 'Mutiscua', 'department_id' => 23,),
            array('code' => '15480', 'name' => 'Muzo', 'department_id' => 7,),
            array('code' => '05483', 'name' => 'Narino', 'department_id' => 2,),
            array('code' => '25483', 'name' => 'Narino', 'department_id' => 15,),
            array('code' => '52480', 'name' => 'Narino', 'department_id' => 22,),
            array('code' => '41483', 'name' => 'Nataga', 'department_id' => 18,),
            array('code' => '73483', 'name' => 'Natagaima', 'department_id' => 30,),
            array('code' => '05495', 'name' => 'Nechi', 'department_id' => 2,),
            array('code' => '05490', 'name' => 'Necocli', 'department_id' => 2,),
            array('code' => '17486', 'name' => 'Neira', 'department_id' => 8,),
            array('code' => '41001', 'name' => 'Neiva', 'department_id' => 18,),
            array('code' => '25486', 'name' => 'Nemocon', 'department_id' => 15,),
            array('code' => '25488', 'name' => 'Nilo', 'department_id' => 15,),
            array('code' => '25489', 'name' => 'Nimaima', 'department_id' => 15,),
            array('code' => '15491', 'name' => 'Nobsa', 'department_id' => 7,),
            array('code' => '25491', 'name' => 'Nocaima', 'department_id' => 15,),
            array('code' => '17495', 'name' => 'Norcasia', 'department_id' => 8,),
            array('code' => '27491', 'name' => 'Novita', 'department_id' => 13,),
            array('code' => '47460', 'name' => 'Nueva Granada', 'department_id' => 20,),
            array('code' => '15494', 'name' => 'Nuevo Colon', 'department_id' => 7,),
            array('code' => '85225', 'name' => 'Nunchia', 'department_id' => 10,),
            array('code' => '27495', 'name' => 'Nuqui', 'department_id' => 13,),
            array('code' => '76497', 'name' => 'Obando', 'department_id' => 31,),
            array('code' => '68498', 'name' => 'Ocamonte', 'department_id' => 28,),
            array('code' => '54498', 'name' => 'Ocana', 'department_id' => 23,),
            array('code' => '68500', 'name' => 'Oiba', 'department_id' => 28,),
            array('code' => '15500', 'name' => 'Oicata', 'department_id' => 7,),
            array('code' => '05501', 'name' => 'Olaya', 'department_id' => 2,),
            array('code' => '52490', 'name' => 'Olaya Herrera', 'department_id' => 22,),
            array('code' => '68502', 'name' => 'Onzaga', 'department_id' => 28,),
            array('code' => '41503', 'name' => 'Oporapa', 'department_id' => 18,),
            array('code' => '86320', 'name' => 'Orito', 'department_id' => 24,),
            array('code' => '85230', 'name' => 'Orocue', 'department_id' => 10,),
            array('code' => '73504', 'name' => 'Ortega', 'department_id' => 30,),
            array('code' => '52506', 'name' => 'Ospina', 'department_id' => 22,),
            array('code' => '15507', 'name' => 'Otanche', 'department_id' => 7,),
            array('code' => '70508', 'name' => 'Ovejas', 'department_id' => 29,),
            array('code' => '15511', 'name' => 'Pachavita', 'department_id' => 7,),
            array('code' => '25513', 'name' => 'Pacho', 'department_id' => 15,),
            array('code' => '97511', 'name' => 'Pacoa', 'department_id' => 32,),
            array('code' => '17513', 'name' => 'Pacora', 'department_id' => 8,),
            array('code' => '19513', 'name' => 'Padilla', 'department_id' => 11,),
            array('code' => '15514', 'name' => 'Paez', 'department_id' => 7,),
            array('code' => '19517', 'name' => 'Paez', 'department_id' => 11,),
            array('code' => '41518', 'name' => 'Paicol', 'department_id' => 18,),
            array('code' => '20517', 'name' => 'Pailitas', 'department_id' => 12,),
            array('code' => '25518', 'name' => 'Paime', 'department_id' => 15,),
            array('code' => '15516', 'name' => 'Paipa', 'department_id' => 7,),
            array('code' => '15518', 'name' => 'Pajarito', 'department_id' => 7,),
            array('code' => '41524', 'name' => 'Palermo', 'department_id' => 18,),
            array('code' => '17524', 'name' => 'Palestina', 'department_id' => 8,),
            array('code' => '41530', 'name' => 'Palestina', 'department_id' => 18,),
            array('code' => '68522', 'name' => 'Palmar', 'department_id' => 28,),
            array('code' => '08520', 'name' => 'Palmar De Varela', 'department_id' => 4,),
            array('code' => '68524', 'name' => 'Palmas Del Socorro', 'department_id' => 28,),
            array('code' => '76520', 'name' => 'Palmira', 'department_id' => 31,),
            array('code' => '70523', 'name' => 'Palmito', 'department_id' => 29,),
            array('code' => '73520', 'name' => 'Palocabildo', 'department_id' => 30,),
            array('code' => '54518', 'name' => 'Pamplona', 'department_id' => 23,),
            array('code' => '54520', 'name' => 'Pamplonita', 'department_id' => 23,),
            array('code' => '94887', 'name' => 'Pana Pana', 'department_id' => 16,),
            array('code' => '25524', 'name' => 'Pandi', 'department_id' => 15,),
            array('code' => '15522', 'name' => 'Panqueba', 'department_id' => 7,),
            array('code' => '97777', 'name' => 'Papunaua', 'department_id' => 32,),
            array('code' => '68533', 'name' => 'Paramo', 'department_id' => 28,),
            array('code' => '25530', 'name' => 'Paratebueno', 'department_id' => 15,),
            array('code' => '25535', 'name' => 'Pasca', 'department_id' => 15,),
            array('code' => '52001', 'name' => 'Pasto', 'department_id' => 22,),
            array('code' => '19532', 'name' => 'Patia', 'department_id' => 11,),
            array('code' => '15531', 'name' => 'Pauna', 'department_id' => 7,),
            array('code' => '15533', 'name' => 'Paya', 'department_id' => 7,),
            array('code' => '85250', 'name' => 'Paz De Ariporo', 'department_id' => 10,),
            array('code' => '15537', 'name' => 'Paz De Rio', 'department_id' => 7,),
            array('code' => '47541', 'name' => 'Pedraza', 'department_id' => 20,),
            array('code' => '20550', 'name' => 'Pelaya', 'department_id' => 12,),
            array('code' => '05541', 'name' => 'Penol', 'department_id' => 2,),
            array('code' => '17541', 'name' => 'Pensilvania', 'department_id' => 8,),
            array('code' => '05543', 'name' => 'Peque', 'department_id' => 2,),
            array('code' => '66001', 'name' => 'Pereira', 'department_id' => 26,),
            array('code' => '15542', 'name' => 'Pesca', 'department_id' => 7,),
            array('code' => '19533', 'name' => 'Piamonte', 'department_id' => 11,),
            array('code' => '68547', 'name' => 'Piedecuesta', 'department_id' => 28,),
            array('code' => '73547', 'name' => 'Piedras', 'department_id' => 30,),
            array('code' => '19548', 'name' => 'Piendamo', 'department_id' => 11,),
            array('code' => '63548', 'name' => 'Pijao', 'department_id' => 25,),
            array('code' => '47545', 'name' => 'Pijino Del Carmen', 'department_id' => 20,),
            array('code' => '68549', 'name' => 'Pinchote', 'department_id' => 28,),
            array('code' => '13549', 'name' => 'Pinillos', 'department_id' => 6,),
            array('code' => '08549', 'name' => 'Piojo', 'department_id' => 4,),
            array('code' => '15550', 'name' => 'Pisba', 'department_id' => 7,),
            array('code' => '41548', 'name' => 'Pital', 'department_id' => 18,),
            array('code' => '41551', 'name' => 'Pitalito', 'department_id' => 18,),
            array('code' => '47551', 'name' => 'Pivijay', 'department_id' => 20,),
            array('code' => '73555', 'name' => 'Planadas', 'department_id' => 30,),
            array('code' => '23555', 'name' => 'Planeta Rica', 'department_id' => 14,),
            array('code' => '47555', 'name' => 'Plato', 'department_id' => 20,),
            array('code' => '52540', 'name' => 'Policarpa', 'department_id' => 22,),
            array('code' => '08558', 'name' => 'Polonuevo', 'department_id' => 4,),
            array('code' => '08560', 'name' => 'Ponedera', 'department_id' => 4,),
            array('code' => '19001', 'name' => 'Popayan', 'department_id' => 11,),
            array('code' => '85263', 'name' => 'Pore', 'department_id' => 10,),
            array('code' => '52560', 'name' => 'Potosi', 'department_id' => 22,),
            array('code' => '76563', 'name' => 'Pradera', 'department_id' => 31,),
            array('code' => '73563', 'name' => 'Prado', 'department_id' => 30,),
            array('code' => '52565', 'name' => 'Providencia', 'department_id' => 22,),
            array('code' => '88564', 'name' => 'Providencia', 'department_id' => 27,),
            array('code' => '20570', 'name' => 'Pueblo Bello', 'department_id' => 12,),
            array('code' => '23570', 'name' => 'Pueblo Nuevo', 'department_id' => 14,),
            array('code' => '66572', 'name' => 'Pueblo Rico', 'department_id' => 26,),
            array('code' => '05576', 'name' => 'Pueblorrico', 'department_id' => 2,),
            array('code' => '47570', 'name' => 'Puebloviejo', 'department_id' => 20,),
            array('code' => '68572', 'name' => 'Puente Nacional', 'department_id' => 28,),
            array('code' => '52573', 'name' => 'Puerres', 'department_id' => 22,),
            array('code' => '91530', 'name' => 'Puerto Alegria', 'department_id' => 1,),
            array('code' => '91536', 'name' => 'Puerto Arica', 'department_id' => 1,),
            array('code' => '86568', 'name' => 'Puerto Asis', 'department_id' => 24,),
            array('code' => '05579', 'name' => 'Puerto Berrio', 'department_id' => 2,),
            array('code' => '15572', 'name' => 'Puerto Boyaca', 'department_id' => 7,),
            array('code' => '86569', 'name' => 'Puerto Caicedo', 'department_id' => 24,),
            array('code' => '99001', 'name' => 'Puerto Carreno', 'department_id' => 33,),
            array('code' => '08573', 'name' => 'Puerto Colombia', 'department_id' => 4,),
            array('code' => '94884', 'name' => 'Puerto Colombia', 'department_id' => 16,),
            array('code' => '50450', 'name' => 'Puerto Concordia', 'department_id' => 21,),
            array('code' => '23574', 'name' => 'Puerto Escondido', 'department_id' => 14,),
            array('code' => '50568', 'name' => 'Puerto Gaitan', 'department_id' => 21,),
            array('code' => '86571', 'name' => 'Puerto Guzman', 'department_id' => 24,),
            array('code' => '23580', 'name' => 'Puerto Libertador', 'department_id' => 14,),
            array('code' => '50577', 'name' => 'Puerto Lleras', 'department_id' => 21,),
            array('code' => '50573', 'name' => 'Puerto Lopez', 'department_id' => 21,),
            array('code' => '05585', 'name' => 'Puerto Nare', 'department_id' => 2,),
            array('code' => '91540', 'name' => 'Puerto Narino', 'department_id' => 1,),
            array('code' => '68573', 'name' => 'Puerto Parra', 'department_id' => 28,),
            array('code' => '18592', 'name' => 'Puerto Rico', 'department_id' => 9,),
            array('code' => '50590', 'name' => 'Puerto Rico', 'department_id' => 21,),
            array('code' => '81591', 'name' => 'Puerto Rondon', 'department_id' => 3,),
            array('code' => '25572', 'name' => 'Puerto Salgar', 'department_id' => 15,),
            array('code' => '54553', 'name' => 'Puerto Santander', 'department_id' => 23,),
            array('code' => '91669', 'name' => 'Puerto Santander', 'department_id' => 1,),
            array('code' => '19573', 'name' => 'Puerto Tejada', 'department_id' => 11,),
            array('code' => '05591', 'name' => 'Puerto Triunfo', 'department_id' => 2,),
            array('code' => '68575', 'name' => 'Puerto Wilches', 'department_id' => 28,),
            array('code' => '25580', 'name' => 'Puli', 'department_id' => 15,),
            array('code' => '52585', 'name' => 'Pupiales', 'department_id' => 22,),
            array('code' => '19585', 'name' => 'Purace', 'department_id' => 11,),
            array('code' => '73585', 'name' => 'Purificacion', 'department_id' => 30,),
            array('code' => '23586', 'name' => 'Purisima', 'department_id' => 14,),
            array('code' => '25592', 'name' => 'Quebradanegra', 'department_id' => 15,),
            array('code' => '25594', 'name' => 'Quetame', 'department_id' => 15,),
            array('code' => '27001', 'name' => 'Quibdo', 'department_id' => 13,),
            array('code' => '63594', 'name' => 'Quimbaya', 'department_id' => 25,),
            array('code' => '66594', 'name' => 'Quinchia', 'department_id' => 26,),
            array('code' => '15580', 'name' => 'Quipama', 'department_id' => 7,),
            array('code' => '25596', 'name' => 'Quipile', 'department_id' => 15,),
            array('code' => '54599', 'name' => 'Ragonvalia', 'department_id' => 23,),
            array('code' => '15599', 'name' => 'Ramiriqui', 'department_id' => 7,),
            array('code' => '15600', 'name' => 'Raquira', 'department_id' => 7,),
            array('code' => '85279', 'name' => 'Recetor', 'department_id' => 10,),
            array('code' => '13580', 'name' => 'Regidor', 'department_id' => 6,),
            array('code' => '05604', 'name' => 'Remedios', 'department_id' => 2,),
            array('code' => '47605', 'name' => 'Remolino', 'department_id' => 20,),
            array('code' => '08606', 'name' => 'Repelon', 'department_id' => 4,),
            array('code' => '50606', 'name' => 'Restrepo', 'department_id' => 21,),
            array('code' => '76606', 'name' => 'Restrepo', 'department_id' => 31,),
            array('code' => '05607', 'name' => 'Retiro', 'department_id' => 2,),
            array('code' => '25612', 'name' => 'Ricaurte', 'department_id' => 15,),
            array('code' => '52612', 'name' => 'Ricaurte', 'department_id' => 22,),
            array('code' => '20614', 'name' => 'Rio De Oro', 'department_id' => 12,),
            array('code' => '27580', 'name' => 'Rio Iro', 'department_id' => 13,),
            array('code' => '27600', 'name' => 'Rio Quito', 'department_id' => 13,),
            array('code' => '13600', 'name' => 'Rio Viejo', 'department_id' => 6,),
            array('code' => '73616', 'name' => 'Rioblanco', 'department_id' => 30,),
            array('code' => '76616', 'name' => 'Riofrio', 'department_id' => 31,),
            array('code' => '44001', 'name' => 'Riohacha', 'department_id' => 19,),
            array('code' => '05615', 'name' => 'Rionegro', 'department_id' => 2,),
            array('code' => '68615', 'name' => 'Rionegro', 'department_id' => 28,),
            array('code' => '17614', 'name' => 'Riosucio', 'department_id' => 8,),
            array('code' => '27615', 'name' => 'Riosucio', 'department_id' => 13,),
            array('code' => '17616', 'name' => 'Risaralda', 'department_id' => 8,),
            array('code' => '41615', 'name' => 'Rivera', 'department_id' => 18,),
            array('code' => '52621', 'name' => 'Roberto Payan', 'department_id' => 22,),
            array('code' => '76622', 'name' => 'Roldanillo', 'department_id' => 31,),
            array('code' => '73622', 'name' => 'Roncesvalles', 'department_id' => 30,),
            array('code' => '15621', 'name' => 'Rondon', 'department_id' => 7,),
            array('code' => '19622', 'name' => 'Rosas', 'department_id' => 11,),
            array('code' => '73624', 'name' => 'Rovira', 'department_id' => 30,),
            array('code' => '68655', 'name' => 'Sabana De Torres', 'department_id' => 28,),
            array('code' => '08634', 'name' => 'Sabanagrande', 'department_id' => 4,),
            array('code' => '05628', 'name' => 'Sabanalarga', 'department_id' => 2,),
            array('code' => '08638', 'name' => 'Sabanalarga', 'department_id' => 4,),
            array('code' => '85300', 'name' => 'Sabanalarga', 'department_id' => 10,),
            array('code' => '47660', 'name' => 'Sabanas De San Angel', 'department_id' => 20,),
            array('code' => '05631', 'name' => 'Sabaneta', 'department_id' => 2,),
            array('code' => '15632', 'name' => 'Saboya', 'department_id' => 7,),
            array('code' => '85315', 'name' => 'Sacama', 'department_id' => 10,),
            array('code' => '15638', 'name' => 'Sachica', 'department_id' => 7,),
            array('code' => '23660', 'name' => 'Sahag;N', 'department_id' => 14,),
            array('code' => '41660', 'name' => 'Saladoblanco', 'department_id' => 18,),
            array('code' => '17653', 'name' => 'Salamina', 'department_id' => 8,),
            array('code' => '47675', 'name' => 'Salamina', 'department_id' => 20,),
            array('code' => '54660', 'name' => 'Salazar', 'department_id' => 23,),
            array('code' => '73671', 'name' => 'Saldana', 'department_id' => 30,),
            array('code' => '63690', 'name' => 'Salento', 'department_id' => 25,),
            array('code' => '05642', 'name' => 'Salgar', 'department_id' => 2,),
            array('code' => '15646', 'name' => 'Samaca', 'department_id' => 7,),
            array('code' => '17662', 'name' => 'Samana', 'department_id' => 8,),
            array('code' => '52678', 'name' => 'Samaniego', 'department_id' => 22,),
            array('code' => '70670', 'name' => 'Sampues', 'department_id' => 29,),
            array('code' => '41668', 'name' => 'San Agustin', 'department_id' => 18,),
            array('code' => '20710', 'name' => 'San Alberto', 'department_id' => 12,),
            array('code' => '05647', 'name' => 'San Andres', 'department_id' => 2,),
            array('code' => '68669', 'name' => 'San Andres', 'department_id' => 28,),
            array('code' => '88001', 'name' => 'San Andres', 'department_id' => 27,),
            array('code' => '23670', 'name' => 'San Andres Sotavento', 'department_id' => 14,),
            array('code' => '23672', 'name' => 'San Antero', 'department_id' => 14,),
            array('code' => '73675', 'name' => 'San Antonio', 'department_id' => 30,),
            array('code' => '25645', 'name' => 'San Antonio Del Tequendama', 'department_id' => 15,),
            array('code' => '68673', 'name' => 'San Benito', 'department_id' => 28,),
            array('code' => '70678', 'name' => 'San Benito Abad', 'department_id' => 29,),
            array('code' => '25649', 'name' => 'San Bernardo', 'department_id' => 15,),
            array('code' => '52685', 'name' => 'San Bernardo', 'department_id' => 22,),
            array('code' => '23675', 'name' => 'San Bernardo Del Viento', 'department_id' => 14,),
            array('code' => '54670', 'name' => 'San Calixto', 'department_id' => 23,),
            array('code' => '05649', 'name' => 'San Carlos', 'department_id' => 2,),
            array('code' => '23678', 'name' => 'San Carlos', 'department_id' => 14,),
            array('code' => '50680', 'name' => 'San Carlos De Guaroa', 'department_id' => 21,),
            array('code' => '25653', 'name' => 'San Cayetano', 'department_id' => 15,),
            array('code' => '54673', 'name' => 'San Cayetano', 'department_id' => 23,),
            array('code' => '13620', 'name' => 'San Cristobal', 'department_id' => 6,),
            array('code' => '20750', 'name' => 'San Diego', 'department_id' => 12,),
            array('code' => '15660', 'name' => 'San Eduardo', 'department_id' => 7,),
            array('code' => '13647', 'name' => 'San Estanislao', 'department_id' => 6,),
            array('code' => '94883', 'name' => 'San Felipe', 'department_id' => 16,),
            array('code' => '13650', 'name' => 'San Fernando', 'department_id' => 6,),
            array('code' => '05652', 'name' => 'San Francisco', 'department_id' => 2,),
            array('code' => '25658', 'name' => 'San Francisco', 'department_id' => 15,),
            array('code' => '86755', 'name' => 'San Francisco', 'department_id' => 24,),
            array('code' => '68679', 'name' => 'San Gil', 'department_id' => 28,),
            array('code' => '13654', 'name' => 'San Jacinto', 'department_id' => 6,),
            array('code' => '13655', 'name' => 'San Jacinto Del Cauca', 'department_id' => 6,),
            array('code' => '05656', 'name' => 'San Jeronimo', 'department_id' => 2,),
            array('code' => '68682', 'name' => 'San Joaquin', 'department_id' => 28,),
            array('code' => '17665', 'name' => 'San Jose', 'department_id' => 8,),
            array('code' => '05658', 'name' => 'San Jose De La Montana', 'department_id' => 2,),
            array('code' => '68684', 'name' => 'San Jose De Miranda', 'department_id' => 28,),
            array('code' => '15664', 'name' => 'San Jose De Pare', 'department_id' => 7,),
            array('code' => '18610', 'name' => 'San Jose Del Fragua', 'department_id' => 9,),
            array('code' => '95001', 'name' => 'San Jose Del Guaviare', 'department_id' => 17,),
            array('code' => '27660', 'name' => 'San Jose Del Palmar', 'department_id' => 13,),
            array('code' => '50683', 'name' => 'San Juan De Arama', 'department_id' => 21,),
            array('code' => '70702', 'name' => 'San Juan De Betulia', 'department_id' => 29,),
            array('code' => '25662', 'name' => 'San Juan De Rio Seco', 'department_id' => 15,),
            array('code' => '05659', 'name' => 'San Juan De Uraba', 'department_id' => 2,),
            array('code' => '44650', 'name' => 'San Juan Del Cesar', 'department_id' => 19,),
            array('code' => '13657', 'name' => 'San Juan Nepomuceno', 'department_id' => 6,),
            array('code' => '50686', 'name' => 'San Juanito', 'department_id' => 21,),
            array('code' => '52687', 'name' => 'San Lorenzo', 'department_id' => 22,),
            array('code' => '05660', 'name' => 'San Luis', 'department_id' => 2,),
            array('code' => '73678', 'name' => 'San Luis', 'department_id' => 30,),
            array('code' => '15667', 'name' => 'San Luis De Gaceno', 'department_id' => 7,),
            array('code' => '85325', 'name' => 'San Luis De Palenque', 'department_id' => 10,),
            array('code' => '70708', 'name' => 'San Marcos', 'department_id' => 29,),
            array('code' => '20770', 'name' => 'San Martin', 'department_id' => 12,),
            array('code' => '50689', 'name' => 'San Martin', 'department_id' => 21,),
            array('code' => '13667', 'name' => 'San Martin De Loba', 'department_id' => 6,),
            array('code' => '15673', 'name' => 'San Mateo', 'department_id' => 7,),
            array('code' => '68686', 'name' => 'San Miguel', 'department_id' => 28,),
            array('code' => '86757', 'name' => 'San Miguel', 'department_id' => 24,),
            array('code' => '15676', 'name' => 'San Miguel De Sema', 'department_id' => 7,),
            array('code' => '70713', 'name' => 'San Onofre', 'department_id' => 29,),
            array('code' => '13670', 'name' => 'San Pablo', 'department_id' => 6,),
            array('code' => '52693', 'name' => 'San Pablo', 'department_id' => 22,),
            array('code' => '15681', 'name' => 'San Pablo De Borbur', 'department_id' => 7,),
            array('code' => '05664', 'name' => 'San Pedro', 'department_id' => 2,),
            array('code' => '70717', 'name' => 'San Pedro', 'department_id' => 29,),
            array('code' => '76670', 'name' => 'San Pedro', 'department_id' => 31,),
            array('code' => '52694', 'name' => 'San Pedro De Cartago', 'department_id' => 22,),
            array('code' => '05665', 'name' => 'San Pedro De Uraba', 'department_id' => 2,),
            array('code' => '23686', 'name' => 'San Pelayo', 'department_id' => 14,),
            array('code' => '05667', 'name' => 'San Rafael', 'department_id' => 2,),
            array('code' => '05670', 'name' => 'San Roque', 'department_id' => 2,),
            array('code' => '19693', 'name' => 'San Sebastian', 'department_id' => 11,),
            array('code' => '47692', 'name' => 'San Sebastian De Buenavista', 'department_id' => 20,),
            array('code' => '05674', 'name' => 'San Vicente', 'department_id' => 2,),
            array('code' => '68689', 'name' => 'San Vicente De Chucuri', 'department_id' => 28,),
            array('code' => '18753', 'name' => 'San Vicente Del Caguan', 'department_id' => 9,),
            array('code' => '47703', 'name' => 'San Zenon', 'department_id' => 20,),
            array('code' => '52683', 'name' => 'Sandona', 'department_id' => 22,),
            array('code' => '47707', 'name' => 'Santa Ana', 'department_id' => 20,),
            array('code' => '05679', 'name' => 'Santa Barbara', 'department_id' => 2,),
            array('code' => '52696', 'name' => 'Santa Barbara', 'department_id' => 22,),
            array('code' => '68705', 'name' => 'Santa Barbara', 'department_id' => 28,),
            array('code' => '47720', 'name' => 'Santa Barbara De Pinto', 'department_id' => 20,),
            array('code' => '13673', 'name' => 'Santa Catalina', 'department_id' => 6,),
            array('code' => '68720', 'name' => 'Santa Helena Del Opon', 'department_id' => 28,),
            array('code' => '73686', 'name' => 'Santa Isabel', 'department_id' => 30,),
            array('code' => '08675', 'name' => 'Santa Lucia', 'department_id' => 4,),
            array('code' => '15690', 'name' => 'Santa Maria', 'department_id' => 7,),
            array('code' => '41676', 'name' => 'Santa Maria', 'department_id' => 18,),
            array('code' => '47001', 'name' => 'Santa Marta', 'department_id' => 20,),
            array('code' => '13683', 'name' => 'Santa Rosa', 'department_id' => 6,),
            array('code' => '19701', 'name' => 'Santa Rosa', 'department_id' => 11,),
            array('code' => '66682', 'name' => 'Santa Rosa De Cabal', 'department_id' => 26,),
            array('code' => '05686', 'name' => 'Santa Rosa De Osos', 'department_id' => 2,),
            array('code' => '15693', 'name' => 'Santa Rosa De Viterbo', 'department_id' => 7,),
            array('code' => '13688', 'name' => 'Santa Rosa Del Sur', 'department_id' => 6,),
            array('code' => '99624', 'name' => 'Santa Rosalia', 'department_id' => 33,),
            array('code' => '15696', 'name' => 'Santa Sofia', 'department_id' => 7,),
            array('code' => '52699', 'name' => 'Santacruz', 'department_id' => 22,),
            array('code' => '05042', 'name' => 'Santafe De Antioquia', 'department_id' => 2,),
            array('code' => '15686', 'name' => 'Santana', 'department_id' => 7,),
            array('code' => '19698', 'name' => 'Santander De Quilichao', 'department_id' => 11,),
            array('code' => '54680', 'name' => 'Santiago', 'department_id' => 23,),
            array('code' => '86760', 'name' => 'Santiago', 'department_id' => 24,),
            array('code' => '70820', 'name' => 'Santiago De Tolu', 'department_id' => 29,),
            array('code' => '05690', 'name' => 'Santo Domingo', 'department_id' => 2,),
            array('code' => '08685', 'name' => 'Santo Tomas', 'department_id' => 4,),
            array('code' => '66687', 'name' => 'Santuario', 'department_id' => 26,),
            array('code' => '52720', 'name' => 'Sapuyes', 'department_id' => 22,),
            array('code' => '81736', 'name' => 'Saravena', 'department_id' => 3,),
            array('code' => '54720', 'name' => 'Sardinata', 'department_id' => 23,),
            array('code' => '25718', 'name' => 'Sasaima', 'department_id' => 15,),
            array('code' => '15720', 'name' => 'Sativanorte', 'department_id' => 7,),
            array('code' => '15723', 'name' => 'Sativasur', 'department_id' => 7,),
            array('code' => '05736', 'name' => 'Segovia', 'department_id' => 2,),
            array('code' => '25736', 'name' => 'Sesquile', 'department_id' => 15,),
            array('code' => '76736', 'name' => 'Sevilla', 'department_id' => 31,),
            array('code' => '15740', 'name' => 'Siachoque', 'department_id' => 7,),
            array('code' => '25740', 'name' => 'Sibate', 'department_id' => 15,),
            array('code' => '86749', 'name' => 'Sibundoy', 'department_id' => 24,),
            array('code' => '54743', 'name' => 'Silos', 'department_id' => 23,),
            array('code' => '25743', 'name' => 'Silvania', 'department_id' => 15,),
            array('code' => '19743', 'name' => 'Silvia', 'department_id' => 11,),
            array('code' => '68745', 'name' => 'Simacota', 'department_id' => 28,),
            array('code' => '25745', 'name' => 'Simijaca', 'department_id' => 15,),
            array('code' => '13744', 'name' => 'Simiti', 'department_id' => 6,),
            array('code' => '70742', 'name' => 'Since', 'department_id' => 29,),
            array('code' => '70001', 'name' => 'Sincelejo', 'department_id' => 29,),
            array('code' => '27745', 'name' => 'Sipi', 'department_id' => 13,),
            array('code' => '47745', 'name' => 'Sitionuevo', 'department_id' => 20,),
            array('code' => '25754', 'name' => 'Soacha', 'department_id' => 15,),
            array('code' => '15753', 'name' => 'Soata', 'department_id' => 7,),
            array('code' => '15757', 'name' => 'Socha', 'department_id' => 7,),
            array('code' => '68755', 'name' => 'Socorro', 'department_id' => 28,),
            array('code' => '15755', 'name' => 'Socota', 'department_id' => 7,),
            array('code' => '15759', 'name' => 'Sogamoso', 'department_id' => 7,),
            array('code' => '18756', 'name' => 'Solano', 'department_id' => 9,),
            array('code' => '08758', 'name' => 'Soledad', 'department_id' => 4,),
            array('code' => '18785', 'name' => 'Solita', 'department_id' => 9,),
            array('code' => '15761', 'name' => 'Somondoco', 'department_id' => 7,),
            array('code' => '05756', 'name' => 'Sonson', 'department_id' => 2,),
            array('code' => '05761', 'name' => 'Sopetran', 'department_id' => 2,),
            array('code' => '13760', 'name' => 'Soplaviento', 'department_id' => 6,),
            array('code' => '25758', 'name' => 'Sopo', 'department_id' => 15,),
            array('code' => '15762', 'name' => 'Sora', 'department_id' => 7,),
            array('code' => '15764', 'name' => 'Soraca', 'department_id' => 7,),
            array('code' => '15763', 'name' => 'Sotaquira', 'department_id' => 7,),
            array('code' => '19760', 'name' => 'Sotara', 'department_id' => 11,),
            array('code' => '68770', 'name' => 'Suaita', 'department_id' => 28,),
            array('code' => '08770', 'name' => 'Suan', 'department_id' => 4,),
            array('code' => '19780', 'name' => 'Suarez', 'department_id' => 11,),
            array('code' => '73770', 'name' => 'Suarez', 'department_id' => 30,),
            array('code' => '41770', 'name' => 'Suaza', 'department_id' => 18,),
            array('code' => '25769', 'name' => 'Subachoque', 'department_id' => 15,),
            array('code' => '19785', 'name' => 'Sucre', 'department_id' => 11,),
            array('code' => '68773', 'name' => 'Sucre', 'department_id' => 28,),
            array('code' => '70771', 'name' => 'Sucre', 'department_id' => 29,),
            array('code' => '25772', 'name' => 'Suesca', 'department_id' => 15,),
            array('code' => '25777', 'name' => 'Supata', 'department_id' => 15,),
            array('code' => '17777', 'name' => 'Supia', 'department_id' => 8,),
            array('code' => '68780', 'name' => 'Surata', 'department_id' => 28,),
            array('code' => '25779', 'name' => 'Susa', 'department_id' => 15,),
            array('code' => '15774', 'name' => 'Susacon', 'department_id' => 7,),
            array('code' => '15776', 'name' => 'Sutamarchan', 'department_id' => 7,),
            array('code' => '25781', 'name' => 'Sutatausa', 'department_id' => 15,),
            array('code' => '15778', 'name' => 'Sutatenza', 'department_id' => 7,),
            array('code' => '25785', 'name' => 'Tabio', 'department_id' => 15,),
            array('code' => '27787', 'name' => 'Tado', 'department_id' => 13,),
            array('code' => '13780', 'name' => 'Talaigua Nuevo', 'department_id' => 6,),
            array('code' => '20787', 'name' => 'Tamalameque', 'department_id' => 12,),
            array('code' => '85400', 'name' => 'Tamara', 'department_id' => 10,),
            array('code' => '81794', 'name' => 'Tame', 'department_id' => 3,),
            array('code' => '05789', 'name' => 'Tamesis', 'department_id' => 2,),
            array('code' => '52786', 'name' => 'Taminango', 'department_id' => 22,),
            array('code' => '52788', 'name' => 'Tangua', 'department_id' => 22,),
            array('code' => '97666', 'name' => 'Taraira', 'department_id' => 32,),
            array('code' => '91798', 'name' => 'Tarapaca', 'department_id' => 1,),
            array('code' => '05790', 'name' => 'Taraza', 'department_id' => 2,),
            array('code' => '41791', 'name' => 'Tarqui', 'department_id' => 18,),
            array('code' => '05792', 'name' => 'Tarso', 'department_id' => 2,),
            array('code' => '15790', 'name' => 'Tasco', 'department_id' => 7,),
            array('code' => '85410', 'name' => 'Tauramena', 'department_id' => 10,),
            array('code' => '25793', 'name' => 'Tausa', 'department_id' => 15,),
            array('code' => '41799', 'name' => 'Tello', 'department_id' => 18,),
            array('code' => '25797', 'name' => 'Tena', 'department_id' => 15,),
            array('code' => '47798', 'name' => 'Tenerife', 'department_id' => 20,),
            array('code' => '25799', 'name' => 'Tenjo', 'department_id' => 15,),
            array('code' => '15798', 'name' => 'Tenza', 'department_id' => 7,),
            array('code' => '54800', 'name' => 'Teorama', 'department_id' => 23,),
            array('code' => '41801', 'name' => 'Teruel', 'department_id' => 18,),
            array('code' => '41797', 'name' => 'Tesalia', 'department_id' => 18,),
            array('code' => '25805', 'name' => 'Tibacuy', 'department_id' => 15,),
            array('code' => '15804', 'name' => 'Tibana', 'department_id' => 7,),
            array('code' => '15806', 'name' => 'Tibasosa', 'department_id' => 7,),
            array('code' => '25807', 'name' => 'Tibirita', 'department_id' => 15,),
            array('code' => '54810', 'name' => 'Tibu', 'department_id' => 23,),
            array('code' => '23807', 'name' => 'Tierralta', 'department_id' => 14,),
            array('code' => '41807', 'name' => 'Timana', 'department_id' => 18,),
            array('code' => '19807', 'name' => 'Timbio', 'department_id' => 11,),
            array('code' => '19809', 'name' => 'Timbiqui', 'department_id' => 11,),
            array('code' => '15808', 'name' => 'Tinjaca', 'department_id' => 7,),
            array('code' => '15810', 'name' => 'Tipacoque', 'department_id' => 7,),
            array('code' => '13810', 'name' => 'Tiquisio', 'department_id' => 6,),
            array('code' => '05809', 'name' => 'Titiribi', 'department_id' => 2,),
            array('code' => '15814', 'name' => 'Toca', 'department_id' => 7,),
            array('code' => '25815', 'name' => 'Tocaima', 'department_id' => 15,),
            array('code' => '25817', 'name' => 'Tocancipa', 'department_id' => 15,),
            array('code' => '15816', 'name' => 'Togni', 'department_id' => 7,),
            array('code' => '05819', 'name' => 'Toledo', 'department_id' => 2,),
            array('code' => '54820', 'name' => 'Toledo', 'department_id' => 23,),
            array('code' => '70823', 'name' => 'Toluviejo', 'department_id' => 29,),
            array('code' => '68820', 'name' => 'Tona', 'department_id' => 28,),
            array('code' => '15820', 'name' => 'Topaga', 'department_id' => 7,),
            array('code' => '25823', 'name' => 'Topaipi', 'department_id' => 15,),
            array('code' => '19821', 'name' => 'Toribio', 'department_id' => 11,),
            array('code' => '76823', 'name' => 'Toro', 'department_id' => 31,),
            array('code' => '15822', 'name' => 'Tota', 'department_id' => 7,),
            array('code' => '19824', 'name' => 'Totoro', 'department_id' => 11,),
            array('code' => '85430', 'name' => 'Trinidad', 'department_id' => 10,),
            array('code' => '76828', 'name' => 'Trujillo', 'department_id' => 31,),
            array('code' => '08832', 'name' => 'Tubara', 'department_id' => 4,),
            array('code' => '76834', 'name' => 'Tulua', 'department_id' => 31,),
            array('code' => '52835', 'name' => 'Tumaco', 'department_id' => 22,),
            array('code' => '15001', 'name' => 'Tunja', 'department_id' => 7,),
            array('code' => '15832', 'name' => 'Tunungua', 'department_id' => 7,),
            array('code' => '52838', 'name' => 'Tuquerres', 'department_id' => 22,),
            array('code' => '13836', 'name' => 'Turbaco', 'department_id' => 6,),
            array('code' => '13838', 'name' => 'Turbana', 'department_id' => 6,),
            array('code' => '05837', 'name' => 'Turbo', 'department_id' => 2,),
            array('code' => '15835', 'name' => 'Turmeque', 'department_id' => 7,),
            array('code' => '15837', 'name' => 'Tuta', 'department_id' => 7,),
            array('code' => '15839', 'name' => 'Tutaza', 'department_id' => 7,),
            array('code' => '25839', 'name' => 'Ubala', 'department_id' => 15,),
            array('code' => '25841', 'name' => 'Ubaque', 'department_id' => 15,),
            array('code' => '76845', 'name' => 'Ulloa', 'department_id' => 31,),
            array('code' => '15842', 'name' => 'Umbita', 'department_id' => 7,),
            array('code' => '25845', 'name' => 'Une', 'department_id' => 15,),
            array('code' => '27800', 'name' => 'Unguia', 'department_id' => 13,),
            array('code' => '27810', 'name' => 'Union Panamericana', 'department_id' => 13,),
            array('code' => '05842', 'name' => 'Uramita', 'department_id' => 2,),
            array('code' => '50370', 'name' => 'Uribe', 'department_id' => 21,),
            array('code' => '44847', 'name' => 'Uribia', 'department_id' => 19,),
            array('code' => '05847', 'name' => 'Urrao', 'department_id' => 2,),
            array('code' => '44855', 'name' => 'Urumita', 'department_id' => 19,),
            array('code' => '08849', 'name' => 'Usiacuri', 'department_id' => 4,),
            array('code' => '25851', 'name' => 'Utica', 'department_id' => 15,),
            array('code' => '05854', 'name' => 'Valdivia', 'department_id' => 2,),
            array('code' => '23855', 'name' => 'Valencia', 'department_id' => 14,),
            array('code' => '68855', 'name' => 'Valle De San Jose', 'department_id' => 28,),
            array('code' => '73854', 'name' => 'Valle De San Juan', 'department_id' => 30,),
            array('code' => '86865', 'name' => 'Valle Del Guamuez', 'department_id' => 24,),
            array('code' => '20001', 'name' => 'Valledupar', 'department_id' => 12,),
            array('code' => '05856', 'name' => 'Valparaiso', 'department_id' => 2,),
            array('code' => '18860', 'name' => 'Valparaiso', 'department_id' => 9,),
            array('code' => '05858', 'name' => 'Vegachi', 'department_id' => 2,),
            array('code' => '68861', 'name' => 'Velez', 'department_id' => 28,),
            array('code' => '73861', 'name' => 'Venadillo', 'department_id' => 30,),
            array('code' => '05861', 'name' => 'Venecia', 'department_id' => 2,),
            array('code' => '25506', 'name' => 'Venecia', 'department_id' => 15,),
            array('code' => '15861', 'name' => 'Ventaquemada', 'department_id' => 7,),
            array('code' => '25862', 'name' => 'Vergara', 'department_id' => 15,),
            array('code' => '76863', 'name' => 'Versalles', 'department_id' => 31,),
            array('code' => '68867', 'name' => 'Vetas', 'department_id' => 28,),
            array('code' => '25867', 'name' => 'Viani', 'department_id' => 15,),
            array('code' => '17867', 'name' => 'Victoria', 'department_id' => 8,),
            array('code' => '05873', 'name' => 'Vigia Del Fuerte', 'department_id' => 2,),
            array('code' => '76869', 'name' => 'Vijes', 'department_id' => 31,),
            array('code' => '54871', 'name' => 'Villa Caro', 'department_id' => 23,),
            array('code' => '15407', 'name' => 'Villa De Leyva', 'department_id' => 7,),
            array('code' => '25843', 'name' => 'Villa De San Diego De Ubate', 'department_id' => 15,),
            array('code' => '54874', 'name' => 'Villa Del Rosario', 'department_id' => 23,),
            array('code' => '19845', 'name' => 'Villa Rica', 'department_id' => 11,),
            array('code' => '86885', 'name' => 'Villagarzon', 'department_id' => 24,),
            array('code' => '25871', 'name' => 'Villagomez', 'department_id' => 15,),
            array('code' => '73870', 'name' => 'Villahermosa', 'department_id' => 30,),
            array('code' => '17873', 'name' => 'Villamaria', 'department_id' => 8,),
            array('code' => '13873', 'name' => 'Villanueva', 'department_id' => 6,),
            array('code' => '44874', 'name' => 'Villanueva', 'department_id' => 19,),
            array('code' => '68872', 'name' => 'Villanueva', 'department_id' => 28,),
            array('code' => '85440', 'name' => 'Villanueva', 'department_id' => 10,),
            array('code' => '25873', 'name' => 'Villapinzon', 'department_id' => 15,),
            array('code' => '73873', 'name' => 'Villarrica', 'department_id' => 30,),
            array('code' => '50001', 'name' => 'Villavicencio', 'department_id' => 21,),
            array('code' => '41872', 'name' => 'Villavieja', 'department_id' => 18,),
            array('code' => '25875', 'name' => 'Villeta', 'department_id' => 15,),
            array('code' => '25878', 'name' => 'Viota', 'department_id' => 15,),
            array('code' => '15879', 'name' => 'Viracacha', 'department_id' => 7,),
            array('code' => '50711', 'name' => 'Vistahermosa', 'department_id' => 21,),
            array('code' => '17877', 'name' => 'Viterbo', 'department_id' => 8,),
            array('code' => '25885', 'name' => 'Yacopi', 'department_id' => 15,),
            array('code' => '52885', 'name' => 'Yacuanquer', 'department_id' => 22,),
            array('code' => '41885', 'name' => 'Yaguara', 'department_id' => 18,),
            array('code' => '05885', 'name' => 'Yali', 'department_id' => 2,),
            array('code' => '05887', 'name' => 'Yarumal', 'department_id' => 2,),
            array('code' => '97889', 'name' => 'Yavarate', 'department_id' => 32,),
            array('code' => '05890', 'name' => 'Yolombo', 'department_id' => 2,),
            array('code' => '05893', 'name' => 'Yondo', 'department_id' => 2,),
            array('code' => '85001', 'name' => 'Yopal', 'department_id' => 10,),
            array('code' => '76890', 'name' => 'Yotoco', 'department_id' => 31,),
            array('code' => '76892', 'name' => 'Yumbo', 'department_id' => 31,),
            array('code' => '13894', 'name' => 'Zambrano', 'department_id' => 6,),
            array('code' => '68895', 'name' => 'Zapatoca', 'department_id' => 28,),
            array('code' => '47960', 'name' => 'Zapayan', 'department_id' => 20,),
            array('code' => '05895', 'name' => 'Zaragoza', 'department_id' => 2,),
            array('code' => '76895', 'name' => 'Zarzal', 'department_id' => 31,),
            array('code' => '15897', 'name' => 'Zetaquira', 'department_id' => 7,),
            array('code' => '25898', 'name' => 'Zipacon', 'department_id' => 15,),
            array('code' => '25899', 'name' => 'Zipaquira', 'department_id' => 15,),
            array('code' => '47980', 'name' => 'Zona Bananera', 'department_id' => 20,),
        );

        DB::table('cities')->insert($cities);
    }
}
