<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CountriesTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        $countries = array(
            array('code' => 'AF', 'name' => 'Afganistán', ),
            array('code' => 'AL', 'name' => 'Albania', ),
            array('code' => 'DE', 'name' => 'Alemania', ),
            array('code' => 'AD', 'name' => 'Andorra', ),
            array('code' => 'AO', 'name' => 'Angola', ),
            array('code' => 'AI', 'name' => 'Anguila', ),
            array('code' => 'AQ', 'name' => 'Antártida', ),
            array('code' => 'AG', 'name' => 'Antigua y Barbuda', ),
            array('code' => 'AN', 'name' => 'Antillas Holandesas', ),
            array('code' => 'SA', 'name' => 'Arabia Saudita', ),
            array('code' => 'DZ', 'name' => 'Argelia', ),
            array('code' => 'AR', 'name' => 'Argentina', ),
            array('code' => 'AM', 'name' => 'Armenia', ),
            array('code' => 'AW', 'name' => 'Aruba', ),
            array('code' => 'AU', 'name' => 'Australia', ),
            array('code' => 'AT', 'name' => 'Austria', ),
            array('code' => 'AZ', 'name' => 'Azerbaiyán', ),
            array('code' => 'BS', 'name' => 'Bahamas', ),
            array('code' => 'BH', 'name' => 'Bahrein', ),
            array('code' => 'BD', 'name' => 'Bangladesh', ),
            array('code' => 'BB', 'name' => 'Barbados', ),
            array('code' => 'BE', 'name' => 'Bélgica', ),
            array('code' => 'BZ', 'name' => 'Belice', ),
            array('code' => 'BJ', 'name' => 'Benin', ),
            array('code' => 'BY', 'name' => 'Bielorrusia', ),
            array('code' => 'BO', 'name' => 'Bolivia', ),
            array('code' => 'BA', 'name' => 'Bosnia y Herzegovina', ),
            array('code' => 'BW', 'name' => 'Botswana', ),
            array('code' => 'BR', 'name' => 'Brasil', ),
            array('code' => 'BN', 'name' => 'Brunei Darussalam', ),
            array('code' => 'BG', 'name' => 'Bulgaria', ),
            array('code' => 'BF', 'name' => 'Burkina Faso', ),
            array('code' => 'BI', 'name' => 'Burundi', ),
            array('code' => 'BT', 'name' => 'Bután', ),
            array('code' => 'CV', 'name' => 'Cabo Verde', ),
            array('code' => 'KH', 'name' => 'Camboya', ),
            array('code' => 'CM', 'name' => 'Camerún', ),
            array('code' => 'CA', 'name' => 'Canadá', ),
            array('code' => 'TD', 'name' => 'Chad', ),
            array('code' => 'CL', 'name' => 'Chile', ),
            array('code' => 'CN', 'name' => 'China', ),
            array('code' => 'CY', 'name' => 'Chipre', ),
            array('code' => 'VA', 'name' => 'Ciudad del Vaticano', ),
            array('code' => 'CO', 'name' => 'Colombia', ),
            array('code' => 'KM', 'name' => 'Comoras', ),
            array('code' => 'CG', 'name' => 'Congo', ),
            array('code' => 'KR', 'name' => 'Corea, Republica de', ),
            array('code' => 'KP', 'name' => 'Corea, República Popular Democrática de', ),
            array('code' => 'CI', 'name' => 'Costa de Marfil', ),
            array('code' => 'CR', 'name' => 'Costa Rica', ),
            array('code' => 'HR', 'name' => 'Croacia (Hrvatska)', ),
            array('code' => 'CU', 'name' => 'Cuba', ),
            array('code' => 'DK', 'name' => 'Dinamarca', ),
            array('code' => 'DJ', 'name' => 'Djibouti', ),
            array('code' => 'DM', 'name' => 'Dominica', ),
            array('code' => 'EC', 'name' => 'Ecudaor', ),
            array('code' => 'EG', 'name' => 'Egipto', ),
            array('code' => 'SV', 'name' => 'El Salvador', ),
            array('code' => 'AE', 'name' => 'Emiratos Árabes Unidos', ),
            array('code' => 'ER', 'name' => 'Eritrea', ),
            array('code' => 'SK', 'name' => 'Eslovaquia', ),
            array('code' => 'SI', 'name' => 'Eslovenia', ),
            array('code' => 'ES', 'name' => 'España', ),
            array('code' => 'US', 'name' => 'Estados Unidos', ),
            array('code' => 'EE', 'name' => 'Estonia', ),
            array('code' => 'ET', 'name' => 'Etiopía', ),
            array('code' => 'RU', 'name' => 'Federación Rusa', ),
            array('code' => 'PH', 'name' => 'Filipinas', ),
            array('code' => 'FI', 'name' => 'Finlandia', ),
            array('code' => 'FJ', 'name' => 'Fiyi', ),
            array('code' => 'FR', 'name' => 'Francia', ),
            array('code' => 'FX', 'name' => 'Francia, Metropolitan', ),
            array('code' => 'GA', 'name' => 'Gabón', ),
            array('code' => 'GM', 'name' => 'Gambia', ),
            array('code' => 'GE', 'name' => 'Georgia', ),
            array('code' => 'GH', 'name' => 'Ghana', ),
            array('code' => 'GI', 'name' => 'Gibraltar', ),
            array('code' => 'GD', 'name' => 'Granada', ),
            array('code' => 'GR', 'name' => 'Grecia', ),
            array('code' => 'GP', 'name' => 'Guadalupe', ),
            array('code' => 'GU', 'name' => 'Guam', ),
            array('code' => 'GT', 'name' => 'Guatemala', ),
            array('code' => 'GY', 'name' => 'Guayana', ),
            array('code' => 'GF', 'name' => 'Guayana francés', ),
            array('code' => 'GN', 'name' => 'Guinea', ),
            array('code' => 'GQ', 'name' => 'Guinea Ecuatorial', ),
            array('code' => 'GW', 'name' => 'Guinea-Bissau', ),
            array('code' => 'HT', 'name' => 'Haití', ),
            array('code' => 'HN', 'name' => 'Honduras', ),
            array('code' => 'HK', 'name' => 'Hong Kong', ),
            array('code' => 'HU', 'name' => 'Hungría', ),
            array('code' => 'IN', 'name' => 'India', ),
            array('code' => 'ID', 'name' => 'Indonesia', ),
            array('code' => 'TG', 'name' => 'Ir', ),
            array('code' => 'IQ', 'name' => 'Irak', ),
            array('code' => 'IR', 'name' => 'Irán (República Islámica de)', ),
            array('code' => 'IE', 'name' => 'Irlanda', ),
            array('code' => 'BV', 'name' => 'Isla Bouvet', ),
            array('code' => 'CX', 'name' => 'Isla de Navidad', ),
            array('code' => 'NF', 'name' => 'Isla Norfork', ),
            array('code' => 'IS', 'name' => 'Islandia', ),
            array('code' => 'BM', 'name' => 'islas Bermudas', ),
            array('code' => 'KY', 'name' => 'Islas Caimán', ),
            array('code' => 'CC', 'name' => 'Islas Cocos (Keeling)', ),
            array('code' => 'CK', 'name' => 'Islas Cook', ),
            array('code' => 'HM', 'name' => 'Islas de Heard y Mc Donald', ),
            array('code' => 'FO', 'name' => 'Islas Faroe', ),
            array('code' => 'GS', 'name' => 'Islas Georgia del Sur Sandwich del Sur', ),
            array('code' => 'FK', 'name' => 'Islas Malvinas', ),
            array('code' => 'MP', 'name' => 'Islas Marianas del Norte', ),
            array('code' => 'MH', 'name' => 'Islas Marshall', ),
            array('code' => 'UM', 'name' => 'Islas menores alejadas de los Estados Unidos', ),
            array('code' => 'SB', 'name' => 'Islas Salomón', ),
            array('code' => 'SJ', 'name' => 'Islas Svalbarn y Jan Mayen', ),
            array('code' => 'TC', 'name' => 'Islas Turcas y Caicos', ),
            array('code' => 'VI', 'name' => 'Islas Vírgenes (EE.UU.)', ),
            array('code' => 'VG', 'name' => 'Islas Vírgenes Británicas', ),
            array('code' => 'WF', 'name' => 'Islas Wallis y Futuna', ),
            array('code' => 'IL', 'name' => 'Israel', ),
            array('code' => 'IT', 'name' => 'Italia', ),
            array('code' => 'LY', 'name' => 'Jamahiriya Arabe Libia', ),
            array('code' => 'JM', 'name' => 'Jamaica', ),
            array('code' => 'JP', 'name' => 'Japón', ),
            array('code' => 'JO', 'name' => 'Jordán', ),
            array('code' => 'QA', 'name' => 'Katar', ),
            array('code' => 'KZ', 'name' => 'Kazajstán', ),
            array('code' => 'KE', 'name' => 'Kenia', ),
            array('code' => 'KG', 'name' => 'Kirguistán', ),
            array('code' => 'KI', 'name' => 'Kiribati', ),
            array('code' => 'KW', 'name' => 'Kuwait', ),
            array('code' => 'LS', 'name' => 'Lesoto', ),
            array('code' => 'LV', 'name' => 'Letonia', ),
            array('code' => 'LB', 'name' => 'Líbano', ),
            array('code' => 'LR', 'name' => 'Liberia', ),
            array('code' => 'LI', 'name' => 'Liechtenstein', ),
            array('code' => 'LT', 'name' => 'Lituania', ),
            array('code' => 'LU', 'name' => 'Luxemburgo', ),
            array('code' => 'MO', 'name' => 'Macau', ),
            array('code' => 'MK', 'name' => 'macedonia', ),
            array('code' => 'MG', 'name' => 'Madagascar', ),
            array('code' => 'MY', 'name' => 'Malasia', ),
            array('code' => 'MW', 'name' => 'Malawi', ),
            array('code' => 'MV', 'name' => 'Maldivas', ),
            array('code' => 'ML', 'name' => 'Mali', ),
            array('code' => 'MT', 'name' => 'Malta', ),
            array('code' => 'MA', 'name' => 'Marruecos', ),
            array('code' => 'MQ', 'name' => 'Martinica', ),
            array('code' => 'MU', 'name' => 'Mauricio', ),
            array('code' => 'MR', 'name' => 'Mauritania', ),
            array('code' => 'TY', 'name' => 'Mayotte', ),
            array('code' => 'MX', 'name' => 'Méjico', ),
            array('code' => 'FM', 'name' => 'Micronesia, Estados Federados de', ),
            array('code' => 'MD', 'name' => 'Moldavia, República de', ),
            array('code' => 'MC', 'name' => 'Mónaco', ),
            array('code' => 'MN', 'name' => 'Mongolia', ),
            array('code' => 'MS', 'name' => 'Montserrat', ),
            array('code' => 'MZ', 'name' => 'Mozambique', ),
            array('code' => 'MM', 'name' => 'Myanmar', ),
            array('code' => 'NA', 'name' => 'Namibia', ),
            array('code' => 'NR', 'name' => 'Nauru', ),
            array('code' => 'NP', 'name' => 'Nepal', ),
            array('code' => 'NI', 'name' => 'Nicaragua', ),
            array('code' => 'NE', 'name' => 'Níger', ),
            array('code' => 'NG', 'name' => 'Nigeria', ),
            array('code' => 'NU', 'name' => 'Niue', ),
            array('code' => 'NO', 'name' => 'Noruega', ),
            array('code' => 'NC', 'name' => 'Nueva Caledonia', ),
            array('code' => 'NZ', 'name' => 'Nueva Zelanda', ),
            array('code' => 'OM', 'name' => 'Omán', ),
            array('code' => 'NL', 'name' => 'Países Bajos', ),
            array('code' => 'PK', 'name' => 'Pakistán', ),
            array('code' => 'PW', 'name' => 'Palau', ),
            array('code' => 'PA', 'name' => 'Panamá', ),
            array('code' => 'PG', 'name' => 'Papúa Nueva Guinea', ),
            array('code' => 'PY', 'name' => 'Paraguay', ),
            array('code' => 'PE', 'name' => 'Perú', ),
            array('code' => 'PN', 'name' => 'Pitcairn', ),
            array('code' => 'PF', 'name' => 'Polinesia francés', ),
            array('code' => 'PL', 'name' => 'Polonia', ),
            array('code' => 'PT', 'name' => 'Portugal', ),
            array('code' => 'PR', 'name' => 'Puerto Rico', ),
            array('code' => 'GB', 'name' => 'Reino Unido', ),
            array('code' => 'SY', 'name' => 'República Árabe Siria', ),
            array('code' => 'CF', 'name' => 'República Centroafricana', ),
            array('code' => 'CZ', 'name' => 'República Checa', ),
            array('code' => 'SS', 'name' => 'República de Sudán del Sur', ),
            array('code' => 'CD', 'name' => 'República Democrática del Congo', ),
            array('code' => 'LA', 'name' => 'República Democrática Popular Lao', ),
            array('code' => 'DO', 'name' => 'República Dominicana', ),
            array('code' => 'RE', 'name' => 'Reunión', ),
            array('code' => 'RW', 'name' => 'Ruanda', ),
            array('code' => 'RO', 'name' => 'Rumania', ),
            array('code' => 'EH', 'name' => 'Sahara Occidental', ),
            array('code' => 'WS', 'name' => 'Samoa', ),
            array('code' => 'AS', 'name' => 'Samoa Americana', ),
            array('code' => 'KN', 'name' => 'San Cristóbal y Nieves', ),
            array('code' => 'SM', 'name' => 'San Marino', ),
            array('code' => 'PM', 'name' => 'San Pedro y Miquelón', ),
            array('code' => 'VC', 'name' => 'San Vicente y las Granadinas', ),
            array('code' => 'SH', 'name' => 'Santa Elena', ),
            array('code' => 'LC', 'name' => 'Santa Lucía', ),
            array('code' => 'ST', 'name' => 'Santo Tomé y Príncipe', ),
            array('code' => 'SN', 'name' => 'Senegal', ),
            array('code' => 'RS', 'name' => 'Serbia', ),
            array('code' => 'SC', 'name' => 'Seychelles', ),
            array('code' => 'SL', 'name' => 'Sierra Leona', ),
            array('code' => 'SG', 'name' => 'Singapur', ),
            array('code' => 'SO', 'name' => 'Somalia', ),
            array('code' => 'LK', 'name' => 'Sri Lanka', ),
            array('code' => 'ZA', 'name' => 'Sudáfrica', ),
            array('code' => 'SD', 'name' => 'Sudán', ),
            array('code' => 'SE', 'name' => 'Suecia', ),
            array('code' => 'CH', 'name' => 'Suiza', ),
            array('code' => 'SR', 'name' => 'Suriname', ),
            array('code' => 'SZ', 'name' => 'Swazilandia', ),
            array('code' => 'TH', 'name' => 'Tailandia', ),
            array('code' => 'TW', 'name' => 'Taiwán', ),
            array('code' => 'TZ', 'name' => 'Tanzania, República Unida de', ),
            array('code' => 'TJ', 'name' => 'Tayikistán', ),
            array('code' => 'IO', 'name' => 'Territorio Británico del Océano Índico', ),
            array('code' => 'TF', 'name' => 'Territorios Franceses del Sur', ),
            array('code' => 'GL', 'name' => 'Tierra Verde', ),
            array('code' => 'TP', 'name' => 'Timor Oriental', ),
            array('code' => 'TK', 'name' => 'Tokelau', ),
            array('code' => 'TO', 'name' => 'Tonga', ),
            array('code' => 'TT', 'name' => 'Trinidad y Tobago', ),
            array('code' => 'TN', 'name' => 'Túnez', ),
            array('code' => 'TM', 'name' => 'Turkmenistán', ),
            array('code' => 'TR', 'name' => 'Turquía', ),
            array('code' => 'TV', 'name' => 'Tuvalu', ),
            array('code' => 'UA', 'name' => 'Ucrania', ),
            array('code' => 'UG', 'name' => 'Uganda', ),
            array('code' => 'UY', 'name' => 'Uruguay', ),
            array('code' => 'UZ', 'name' => 'Uzbekistán', ),
            array('code' => 'VU', 'name' => 'Vanuatu', ),
            array('code' => 'VE', 'name' => 'Venezuela', ),
            array('code' => 'VN', 'name' => 'Vietnam', ),
            array('code' => 'YE', 'name' => 'Yemen', ),
            array('code' => 'YU', 'name' => 'Yugoslavia', ),
            array('code' => 'ZR', 'name' => 'Zaire', ),
            array('code' => 'ZM', 'name' => 'Zambia', ),
            array('code' => 'ZW', 'name' => 'Zimbabue', ),
        );

        DB::table('countries')->insert($countries);
    }
}
